// Provider-neutral IDs only. Native mappings are checked against this list.
export const achievementIds = [
  "achievement.first_bot",
  "achievement.first_assembly_line",
  "achievement.first_data_center",
  "achievement.first_planet",
  "achievement.first_influence",
  "achievement.first_infinity_point",
  "achievement.first_quantum_shard",
  "achievement.first_strange_matter",
  "achievement.first_ai_manager",
  "achievement.first_server",
  "achievement.secrets_of_universe_maxed",
  "achievement.divisions_complete",
  "achievement.unlock_terra",
  "achievement.unlock_purity",
  "achievement.unlock_power",
  "achievement.unlock_stellar",
  "achievement.unlock_paragade",
  "achievement.unlock_avocato",
  "achievement.counteractions_complete",
  "achievement.speed_upgrades_complete",
  "achievement.translation_upgrades_complete",
  "achievement.simulation_upgrades_complete",
  "achievement.developer_options",
  "achievement.avotation_secrets_complete",
  "achievement.avocados_skill",
  "achievement.bots_42qi",
  "achievement.skill_points_42"
] as const
