import { createHash } from 'node:crypto'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import type { Plugin, ResolvedConfig, Rollup } from 'vite'

type OutputAsset = Rollup.OutputAsset
type OutputBundle = Rollup.OutputBundle
type OutputChunk = Rollup.OutputChunk

export const PWA_BASE_PATH = '/play/'
const PWA_GENERATOR_VERSION = '2'

const PUBLIC_PRECACHE_FILES = Object.freeze([
  'manifest.webmanifest',
  'icons/pwa-icon.svg',
  'icons/pwa-icon-192.png',
  'icons/pwa-icon-512.png',
  'icons/pwa-maskable-512.png',
])

export function pwaPackagePlugin(): Plugin {
  let config: ResolvedConfig | undefined
  return {
    name: 'idle-dyson-swarm-pwa-package',
    apply: 'build',
    configResolved(resolved) {
      config = resolved
      assertPwaBasePath(resolved.base)
    },
    generateBundle(_options, bundle) {
      if (config === undefined) {
        throw new Error('PWA packaging requires resolved Vite configuration.')
      }
      const precacheUrls = collectPwaPrecacheUrls(bundle, config.base)
      const cacheVersion = hashPwaPackage(
        bundle,
        config.publicDir,
      )
      this.emitFile({
        type: 'asset',
        fileName: 'service-worker.js',
        source: renderPwaServiceWorker({
          basePath: config.base,
          cacheVersion,
          precacheUrls,
        }),
      })
    },
  }
}

export function assertPwaBasePath(basePath: string): void {
  if (basePath !== PWA_BASE_PATH) {
    throw new Error(
      `The installable Web release must be built at ${PWA_BASE_PATH}; received ${basePath}.`,
    )
  }
}

export function collectPwaPrecacheUrls(
  bundle: OutputBundle,
  basePath = PWA_BASE_PATH,
): readonly string[] {
  assertPwaBasePath(basePath)
  const emittedFiles = Object.values(bundle)
    .map((output) => output.fileName)
    .filter(isPlayerFacingBuildAsset)
    .map((fileName) => `${basePath}${fileName}`)
  return Object.freeze([
    basePath,
    ...PUBLIC_PRECACHE_FILES.map((fileName) => `${basePath}${fileName}`),
    ...emittedFiles,
  ].filter((url, index, urls) => urls.indexOf(url) === index).sort())
}

export interface PwaServiceWorkerOptions {
  readonly basePath: string
  readonly cacheVersion: string
  readonly precacheUrls: readonly string[]
}

export function renderPwaServiceWorker({
  basePath,
  cacheVersion,
  precacheUrls,
}: PwaServiceWorkerOptions): string {
  assertPwaBasePath(basePath)
  const cachePrefix = 'idle-dyson-swarm-app-'
  const cacheName = `${cachePrefix}${cacheVersion}`
  return `/* Generated by scripts/pwaPackage.ts. */
const CACHE_PREFIX = ${JSON.stringify(cachePrefix)};
const CACHE_NAME = ${JSON.stringify(cacheName)};
const SCOPE_PATH = ${JSON.stringify(basePath)};
const APP_SHELL_URL = ${JSON.stringify(basePath)};
const PRECACHE_URLS = Object.freeze(${JSON.stringify(precacheUrls, null, 2)});
const PRECACHE_PATHS = new Set(PRECACHE_URLS.map((url) => new URL(url, self.location.origin).pathname));

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE_NAME).then((cache) => cache.addAll(PRECACHE_URLS)));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys
        .filter((key) => key.startsWith(CACHE_PREFIX) && key !== CACHE_NAME)
        .map((key) => caches.delete(key))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('message', (event) => {
  if (event.data?.type === 'ACTIVATE_UPDATE') void self.skipWaiting();
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin || !url.pathname.startsWith(SCOPE_PATH)) return;

  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request).catch(async () =>
        (await caches.match(APP_SHELL_URL)) ?? Response.error()),
    );
    return;
  }

  if (!PRECACHE_PATHS.has(url.pathname)) return;
  event.respondWith(
    caches.match(url.pathname, { ignoreSearch: true })
      .then((cached) => cached ?? fetch(request)),
  );
});
`
}

function isPlayerFacingBuildAsset(fileName: string): boolean {
  return (
    fileName !== 'index.html' &&
    fileName !== '_headers' &&
    fileName !== 'service-worker.js' &&
    !fileName.startsWith('.vite/') &&
    !fileName.endsWith('.map')
  )
}

export function hashPwaPackage(
  bundle: OutputBundle,
  publicDirectory: string,
): string {
  const hash = createHash('sha256')
  hash.update(PWA_GENERATOR_VERSION)
  for (const output of Object.values(bundle).sort(compareOutputFileNames)) {
    if (!isPwaVersionedBuildAsset(output.fileName)) continue
    hash.update(output.fileName)
    hash.update(outputBytes(output))
  }
  for (const fileName of PUBLIC_PRECACHE_FILES) {
    hash.update(fileName)
    hash.update(readFileSync(resolve(publicDirectory, fileName)))
  }
  return hash.digest('hex').slice(0, 16)
}

function isPwaVersionedBuildAsset(fileName: string): boolean {
  return (
    fileName !== '_headers' &&
    fileName !== 'service-worker.js' &&
    !fileName.startsWith('.vite/') &&
    !fileName.endsWith('.map')
  )
}

function compareOutputFileNames(
  left: OutputAsset | OutputChunk,
  right: OutputAsset | OutputChunk,
): number {
  return left.fileName.localeCompare(right.fileName)
}

function outputBytes(output: OutputAsset | OutputChunk): string | Uint8Array {
  if (output.type === 'chunk') return output.code
  return typeof output.source === 'string'
    ? output.source
    : new Uint8Array(output.source)
}
