import { cloneCanonicalGameStateV2 } from '../game-state/cloneV2'
import { cloneCanonicalRuntimeSidecarV2, type CanonicalRuntimeSidecarV2 } from '../game-state/runtimeV2'
import type { CanonicalGameStateV2 } from '../game-state/typesV2'
import { validateCanonicalGameStateV2 } from '../game-state/validateV2'
import {
  GAME_DECIMAL_ONE,GAME_DECIMAL_ZERO,addGameDecimals,cloneGameDecimal,
  compareGameDecimals,equalGameDecimals,gameDecimalFromNumber,logGameDecimal,
  multiplyGameDecimals,subtractGameDecimals,type GameDecimal,
} from '../math/gameDecimal'
import { deriveDysonV2FromCauses } from './dysonV2Derivation'
import { DISCRETE_MAXIMUM } from './numeric'

export type AvocadoFeedSourceV2='infinity-points'|'influence'|'strange-matter'
export interface AvocadoPublicationV2{readonly revision:number;readonly state:CanonicalGameStateV2;readonly runtime:CanonicalRuntimeSidecarV2}
export type AvocadoCommandV2=Readonly<{kind:'feed-all';source:AvocadoFeedSourceV2}>|Readonly<{kind:'meditation-step';stepIndex:number}>
export interface AvocadoCommandQuoteV2{readonly kind:'avocado-command-quote-v2';readonly accepted:boolean;readonly code:'ready'|'invalid-request'|'locked'|'empty'|'output-unrepresented'|'wrong-step'|'already-complete'|'revision-exhausted';readonly sourceRevision:number;readonly commandKind:AvocadoCommandV2['kind']|null;readonly feedSource:AvocadoFeedSourceV2|null;readonly transferred:GameDecimal;readonly effectiveCredit:GameDecimal;readonly skillPointsGranted:bigint;readonly expectedPublication:Readonly<AvocadoPublicationV2>|null}
export interface AvocadoCommandCommitV2{readonly accepted:boolean;readonly changed:boolean;readonly code:'committed'|'quote-rejected'|'stale-publication';readonly publication:Readonly<AvocadoPublicationV2>|null}
export interface AvocadoMultiplierV2{readonly infinityPoints:GameDecimal;readonly influence:GameDecimal;readonly strangeMatter:GameDecimal;readonly overflow:GameDecimal;readonly total:GameDecimal}
export interface AvocadoStrangeMatterAccountV2{readonly kind:'avocado-strange-matter-account-v2';readonly revision:number;readonly balance:GameDecimal}
interface Issued{readonly source:Readonly<AvocadoPublicationV2>;readonly candidate:Readonly<AvocadoPublicationV2>}
const issued=new WeakMap<object,Issued>(),consumed=new WeakSet<object>(),issuedMatterAccounts=new WeakMap<object,Readonly<{revision:number;balance:GameDecimal}>>()
const TEN=gameDecimalFromNumber(10),FOUR=4n

/** @internal The application Dream-currency owner is the sole intended issuer. */
export function registerAvocadoStrangeMatterAccountV2ForOwner(revision:number,balance:GameDecimal):Readonly<AvocadoStrangeMatterAccountV2>{if(!Number.isSafeInteger(revision)||revision<0||Object.is(revision,-0))throw new TypeError('Avocato Strange Matter revision is invalid.');const account=Object.freeze({kind:'avocado-strange-matter-account-v2' as const,revision,balance:cloneGameDecimal(balance)});issuedMatterAccounts.set(account,Object.freeze({revision,balance:cloneGameDecimal(balance)}));return account}

export function deriveAvocadoMultiplierV2(state:Readonly<CanonicalGameStateV2>):Readonly<AvocadoMultiplierV2>{if(!validateCanonicalGameStateV2(state).valid)throw new TypeError('Invalid state for Avocato multiplier.');if(!state.avocado.unlocked)return multiplier(GAME_DECIMAL_ONE,GAME_DECIMAL_ONE,GAME_DECIMAL_ONE,GAME_DECIMAL_ONE);const ip=logContribution(state.avocado.infinityPoints),influence=logContribution(state.avocado.influence),matter=logContribution(state.avocado.strangeMatter),overflow=compareGameDecimals(state.avocado.overflowMultiplier,GAME_DECIMAL_ONE)>=0?addGameDecimals(GAME_DECIMAL_ONE,state.avocado.overflowMultiplier):GAME_DECIMAL_ONE;return multiplier(ip,influence,matter,overflow)}
export function quoteAvocadoCommandV2(publication:Readonly<AvocadoPublicationV2>,request:AvocadoCommandV2,matterAccount:Readonly<AvocadoStrangeMatterAccountV2>|null=null):Readonly<AvocadoCommandQuoteV2>{try{return quoteInternal(publication,request,matterAccount)}catch{return failureQuote('invalid-request')}}
export function commitAvocadoCommandV2(quote:Readonly<AvocadoCommandQuoteV2>,publication:Readonly<AvocadoPublicationV2>):Readonly<AvocadoCommandCommitV2>{try{if(quote===null||typeof quote!=='object'||consumed.has(quote as object))return commitFailure('quote-rejected');const descriptor=issued.get(quote as object);if(descriptor===undefined)return commitFailure('quote-rejected');consumed.add(quote as object);const current=admitPublication(publication);if(current===null||!equalTree(current,descriptor.source))return commitFailure('stale-publication');return Object.freeze({accepted:true,changed:true,code:'committed' as const,publication:descriptor.candidate})}catch{return commitFailure('quote-rejected')}}

function quoteInternal(publication:Readonly<AvocadoPublicationV2>,request:AvocadoCommandV2,matterAccount:Readonly<AvocadoStrangeMatterAccountV2>|null):Readonly<AvocadoCommandQuoteV2>{const source=admitPublication(publication),captured=captureRequest(request);if(source===null||captured===null)return failureQuote('invalid-request');if(source.revision===Number.MAX_SAFE_INTEGER)return failureQuote('revision-exhausted',source.revision,captured.kind,captured.kind==='feed-all'?captured.source:null);const outcome=captured.kind==='feed-all'?feed(source,captured.source,matterAccount):meditate(source,captured.stepIndex);if(outcome.code!=='ready')return failureQuote(outcome.code,source.revision,captured.kind,captured.kind==='feed-all'?captured.source:null);const state=cloneCanonicalGameStateV2(outcome.state),derived=deriveDysonV2FromCauses(state,source.runtime),runtime=cloneCanonicalRuntimeSidecarV2(Object.freeze({dysonEvaluationSnapshot:derived.nextEvaluationSnapshot,dysonTuningProfile:source.runtime.dysonTuningProfile})),expected=Object.freeze({revision:source.revision+1,state,runtime}),quote=Object.freeze({kind:'avocado-command-quote-v2' as const,accepted:true,code:'ready' as const,sourceRevision:source.revision,commandKind:captured.kind,feedSource:captured.kind==='feed-all'?captured.source:null,transferred:outcome.transferred,effectiveCredit:outcome.credit,skillPointsGranted:outcome.skillPoints,expectedPublication:expected});issued.set(quote,Object.freeze({source,candidate:expected}));return quote}
type Outcome=Readonly<{code:'ready';state:CanonicalGameStateV2;transferred:GameDecimal;credit:GameDecimal;skillPoints:bigint}>|Readonly<{code:'locked'|'empty'|'output-unrepresented'|'wrong-step'|'already-complete'}>
function feed(source:Readonly<AvocadoPublicationV2>,kind:AvocadoFeedSourceV2,matterAccount:Readonly<AvocadoStrangeMatterAccountV2>|null):Outcome{if(!source.state.avocado.unlocked)return Object.freeze({code:'locked'});const amount=kind==='infinity-points'?source.state.infinity.availablePoints:kind==='influence'?source.state.reality.influence:source.state.dream.strangeMatter;if(compareGameDecimals(amount,GAME_DECIMAL_ZERO)<=0)return Object.freeze({code:'empty'});if(kind==='strange-matter'&&!validMatterAccount(matterAccount,source.revision,amount))return Object.freeze({code:'locked'});const current=kind==='infinity-points'?source.state.avocado.infinityPoints:kind==='influence'?source.state.avocado.influence:source.state.avocado.strangeMatter,next=addGameDecimals(current,amount);if(equalGameDecimals(next,current))return Object.freeze({code:'output-unrepresented'});const credit=subtractGameDecimals(next,current),avocado={...source.state.avocado,[kind==='infinity-points'?'infinityPoints':kind==='influence'?'influence':'strangeMatter']:next};let state:CanonicalGameStateV2;if(kind==='infinity-points')state={...source.state,infinity:{...source.state.infinity,availablePoints:GAME_DECIMAL_ZERO},avocado};else if(kind==='influence')state={...source.state,reality:{...source.state.reality,influence:GAME_DECIMAL_ZERO},avocado};else state={...source.state,dream:{...source.state.dream,strangeMatter:GAME_DECIMAL_ZERO},avocado};return Object.freeze({code:'ready',state,transferred:cloneGameDecimal(amount),credit,skillPoints:0n})}
function meditate(source:Readonly<AvocadoPublicationV2>,stepIndex:number):Outcome{if(!source.state.avocado.unlocked)return Object.freeze({code:'locked'});if(source.state.secretProgress.completed)return Object.freeze({code:'already-complete'});if(source.state.secretProgress.step!==stepIndex)return Object.freeze({code:'wrong-step'});const final=stepIndex===6,headroom=DISCRETE_MAXIMUM-source.state.skills.points,granted=final?(headroom<FOUR?headroom:FOUR):0n;const state=cloneCanonicalGameStateV2({...source.state,skills:final?{...source.state.skills,points:source.state.skills.points+granted}:source.state.skills,secretProgress:{completed:final,step:stepIndex+1}});return Object.freeze({code:'ready',state,transferred:GAME_DECIMAL_ZERO,credit:GAME_DECIMAL_ZERO,skillPoints:granted})}
function validMatterAccount(value:unknown,revision:number,balance:GameDecimal):boolean{if(value===null||typeof value!=='object')return false;const descriptor=issuedMatterAccounts.get(value as object);return descriptor!==undefined&&descriptor.revision===revision&&equalGameDecimals(descriptor.balance,balance)}
function logContribution(value:GameDecimal):GameDecimal{return compareGameDecimals(value,TEN)>=0?logGameDecimal(value,10):cloneGameDecimal(GAME_DECIMAL_ONE)}
function multiplier(ip:GameDecimal,influence:GameDecimal,matter:GameDecimal,overflow:GameDecimal):Readonly<AvocadoMultiplierV2>{return Object.freeze({infinityPoints:cloneGameDecimal(ip),influence:cloneGameDecimal(influence),strangeMatter:cloneGameDecimal(matter),overflow:cloneGameDecimal(overflow),total:multiplyGameDecimals(multiplyGameDecimals(multiplyGameDecimals(ip,influence),matter),overflow)})}
function admitPublication(value:unknown):Readonly<AvocadoPublicationV2>|null{const record=closed(value,['revision','state','runtime']);if(record===null||typeof record.revision!=='number'||!Number.isSafeInteger(record.revision)||record.revision<0||Object.is(record.revision,-0)||!validateCanonicalGameStateV2(record.state).valid)return null;try{return Object.freeze({revision:record.revision,state:cloneCanonicalGameStateV2(record.state as CanonicalGameStateV2),runtime:cloneCanonicalRuntimeSidecarV2(record.runtime as CanonicalRuntimeSidecarV2)})}catch{return null}}
function captureRequest(value:unknown):AvocadoCommandV2|null{if(value===null||typeof value!=='object')return null;const kindDescriptor=Object.getOwnPropertyDescriptor(value,'kind');if(kindDescriptor===undefined||!('value'in kindDescriptor))return null;if(kindDescriptor.value==='feed-all'){const record=closed(value,['kind','source']);return record!==null&&(record.source==='infinity-points'||record.source==='influence'||record.source==='strange-matter')?Object.freeze({kind:'feed-all',source:record.source}):null}if(kindDescriptor.value==='meditation-step'){const record=closed(value,['kind','stepIndex']);return record!==null&&typeof record.stepIndex==='number'&&Number.isSafeInteger(record.stepIndex)&&record.stepIndex>=0&&record.stepIndex<7&&!Object.is(record.stepIndex,-0)?Object.freeze({kind:'meditation-step',stepIndex:record.stepIndex}):null}return null}
function closed(value:unknown,keys:readonly string[]):Readonly<Record<string,unknown>>|null{if(value===null||typeof value!=='object'||Array.isArray(value)||Object.getPrototypeOf(value)!==Object.prototype)return null;const descriptors=Object.getOwnPropertyDescriptors(value),actual=Reflect.ownKeys(descriptors);if(actual.length!==keys.length||actual.some(key=>typeof key!=='string'||!keys.includes(key))||keys.some(key=>descriptors[key]===undefined||!descriptors[key]!.enumerable||!('value'in descriptors[key]!)))return null;return Object.freeze(Object.fromEntries(keys.map(key=>[key,descriptors[key]!.value])))}
function equalTree(a:unknown,b:unknown):boolean{if(Object.is(a,b))return true;if(a===null||b===null||typeof a!=='object'||typeof b!=='object'||Object.getPrototypeOf(a)!==Object.getPrototypeOf(b))return false;const ak=Reflect.ownKeys(a),bk=Reflect.ownKeys(b);return ak.length===bk.length&&ak.every(key=>bk.includes(key)&&equalTree(Object.getOwnPropertyDescriptor(a,key)?.value,Object.getOwnPropertyDescriptor(b,key)?.value))}
function failureQuote(code:AvocadoCommandQuoteV2['code'],sourceRevision=-1,commandKind:AvocadoCommandQuoteV2['commandKind']=null,feedSource:AvocadoFeedSourceV2|null=null):Readonly<AvocadoCommandQuoteV2>{return Object.freeze({kind:'avocado-command-quote-v2',accepted:false,code,sourceRevision,commandKind,feedSource,transferred:GAME_DECIMAL_ZERO,effectiveCredit:GAME_DECIMAL_ZERO,skillPointsGranted:0n,expectedPublication:null})}
function commitFailure(code:AvocadoCommandCommitV2['code']):Readonly<AvocadoCommandCommitV2>{return Object.freeze({accepted:false,changed:false,code,publication:null})}
