import { readdirSync,readFileSync } from 'node:fs'
import { dirname,join,relative } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe,expect,test } from 'vitest'
import ts from 'typescript'
import { cloneCanonicalGameStateV2 } from '../game-state/cloneV2'
import { migratePreparedSaveToV2 } from '../game-state/mappingV2'
import type { CanonicalGameStateV2 } from '../game-state/typesV2'
import { gameDecimalFromCanonicalString,gameDecimalFromNumber,gameDecimalToCanonicalString } from '../math/gameDecimal'
import { PreparedSave } from '../save/prepare'
import { deserializeWebSave } from '../save/serialization'
import schema12Web from '../../test/fixtures/schema-12-canonical-idsweb1-first-run.txt?raw'
import { commitAvocadoCommandV2,deriveAvocadoMultiplierV2,previewPreparedAvocadoFeedV2,previewPreparedAvocadoMeditationV2,quoteAvocadoCommandV2,registerAvocadoStrangeMatterAccountV2ForOwner } from './avocadoV2'
import { DISCRETE_MAXIMUM } from './numeric'

const migrated=migratePreparedSaveToV2(PreparedSave.fromDecoded(deserializeWebSave(schema12Web)),Object.freeze({kind:'trusted-same-device' as const})),base=migrated.state,runtime=migrated.runtime,d=(value:string)=>value.includes('e')?gameDecimalFromCanonicalString(value):gameDecimalFromNumber(Number(value))
function stateWith(options:Readonly<{unlocked?:boolean;ip?:string;influence?:string;matter?:string;avoIp?:string;avoInfluence?:string;avoMatter?:string;overflow?:string;step?:number;complete?:boolean;points?:bigint}>= {}):CanonicalGameStateV2{return cloneCanonicalGameStateV2({...base,infinity:{...base.infinity,availablePoints:d(options.ip??'0')},reality:{...base.reality,influence:d(options.influence??'0')},dream:{...base.dream,strangeMatter:d(options.matter??'0')},avocado:{...base.avocado,unlocked:options.unlocked??true,infinityPoints:d(options.avoIp??'0'),influence:d(options.avoInfluence??'0'),strangeMatter:d(options.avoMatter??'0'),overflowMultiplier:d(options.overflow??'0')},secretProgress:{completed:options.complete??false,step:options.step??0},skills:{...base.skills,points:options.points??base.skills.points}})}
const publication=(state:CanonicalGameStateV2,revision=1)=>Object.freeze({revision,state,runtime})

describe('Avocato V2',()=>{
  test('previews feed and meditation without issuing commit-capable publications',()=>{const state=stateWith({ip:'42',matter:'500',step:6,points:3n});expect(previewPreparedAvocadoFeedV2(state,'infinity-points')).toMatchObject({accepted:true,code:'ready',skillPointsGranted:0n});expect(gameDecimalToCanonicalString(previewPreparedAvocadoFeedV2(state,'infinity-points').transferred)).toBe('4.2e1');expect(previewPreparedAvocadoFeedV2(state,'strange-matter').code).toBe('locked');expect(previewPreparedAvocadoFeedV2(state,'strange-matter',true)).toMatchObject({accepted:true,code:'ready'});expect(previewPreparedAvocadoMeditationV2(state,6)).toMatchObject({accepted:true,code:'ready',skillPointsGranted:4n})})

  test.each([['infinity-points','42','0','0','infinityPoints'],['influence','0','84','0','influence']] as const)('atomically feeds all %s and zeros only the source',(source,ip,influence,matter,target)=>{const state=stateWith({ip,influence,matter}),origin=publication(state,4),quote=quoteAvocadoCommandV2(origin,Object.freeze({kind:'feed-all',source}));expect(quote).toMatchObject({accepted:true,code:'ready',sourceRevision:4,feedSource:source,expectedPublication:{revision:5}});const next=commitAvocadoCommandV2(quote,origin).publication!.state;expect(gameDecimalToCanonicalString(next.avocado[target])).toBe(source==='infinity-points'?'4.2e1':'8.4e1');expect(gameDecimalToCanonicalString(source==='infinity-points'?next.infinity.availablePoints:next.reality.influence)).toBe('0');expect(next.dream.strangeMatter).toEqual(state.dream.strangeMatter)})

  test('requires the sole locally issued Strange Matter account',()=>{const state=stateWith({matter:'500'}),origin=publication(state,7),request=Object.freeze({kind:'feed-all' as const,source:'strange-matter' as const});expect(quoteAvocadoCommandV2(origin,request).code).toBe('locked');expect(quoteAvocadoCommandV2(origin,request,Object.freeze({kind:'avocado-strange-matter-account-v2',revision:7,balance:d('500')})).code).toBe('locked');const account=registerAvocadoStrangeMatterAccountV2ForOwner(7,state.dream.strangeMatter),quote=quoteAvocadoCommandV2(origin,request,account),next=commitAvocadoCommandV2(quote,origin).publication!.state;expect(gameDecimalToCanonicalString(next.dream.strangeMatter)).toBe('0');expect(gameDecimalToCanonicalString(next.avocado.strangeMatter)).toBe('5e2')})

  test('rejects empty, locked and unrepresented feed-all without debiting',()=>{expect(quoteAvocadoCommandV2(publication(stateWith({unlocked:false,ip:'1'})),Object.freeze({kind:'feed-all',source:'infinity-points'})).code).toBe('locked');expect(quoteAvocadoCommandV2(publication(stateWith()),Object.freeze({kind:'feed-all',source:'influence'})).code).toBe('empty');const saturated=stateWith({ip:'1',avoIp:'1e1000'}),quote=quoteAvocadoCommandV2(publication(saturated),Object.freeze({kind:'feed-all',source:'infinity-points'}));expect(quote).toMatchObject({accepted:false,code:'output-unrepresented',expectedPublication:null});expect(gameDecimalToCanonicalString(saturated.infinity.availablePoints)).toBe('1e0')})

  test('derives Decimal-native log contributions in authored order above 1e308',()=>{const result=deriveAvocadoMultiplierV2(stateWith({avoIp:'1e1000',avoInfluence:'1e500',avoMatter:'1e100',overflow:'2'}));expect(gameDecimalToCanonicalString(result.infinityPoints)).toBe('1e3');expect(gameDecimalToCanonicalString(result.influence)).toBe('5e2');expect(gameDecimalToCanonicalString(result.strangeMatter)).toBe('1e2');expect(gameDecimalToCanonicalString(result.overflow)).toBe('3e0');expect(gameDecimalToCanonicalString(result.total)).toBe('1.5e8');const neutral=deriveAvocadoMultiplierV2(stateWith({avoIp:'9',avoInfluence:'0',avoMatter:'1',overflow:'.999'}));expect(gameDecimalToCanonicalString(neutral.total)).toBe('1e0');expect(gameDecimalToCanonicalString(deriveAvocadoMultiplierV2(stateWith({unlocked:false,avoIp:'1e1000'})).total)).toBe('1e0')})

  test('advances the exact seven-step meditation and grants four Skill Points once',()=>{let current=publication(stateWith({points:3n}),10);for(let step=0;step<7;step+=1){const quote=quoteAvocadoCommandV2(current,Object.freeze({kind:'meditation-step',stepIndex:step}));expect(quote.accepted).toBe(true);expect(quote.skillPointsGranted).toBe(step===6?4n:0n);const commit=commitAvocadoCommandV2(quote,current);current=commit.publication!}expect(current.state.secretProgress).toEqual({completed:true,step:7});expect(current.state.skills.points).toBe(7n);expect(quoteAvocadoCommandV2(current,Object.freeze({kind:'meditation-step',stepIndex:6})).code).toBe('already-complete')})

  test('requires access, rejects wrong order and saturates the represented final reward',()=>{expect(quoteAvocadoCommandV2(publication(stateWith({unlocked:false})),Object.freeze({kind:'meditation-step',stepIndex:0})).code).toBe('locked');expect(quoteAvocadoCommandV2(publication(stateWith({step:2})),Object.freeze({kind:'meditation-step',stepIndex:1})).code).toBe('wrong-step');for(const [points,granted] of [[DISCRETE_MAXIMUM-2n,2n],[DISCRETE_MAXIMUM,0n]] as const){const source=publication(stateWith({step:6,points})),quote=quoteAvocadoCommandV2(source,Object.freeze({kind:'meditation-step',stepIndex:6}));expect(quote).toMatchObject({accepted:true,code:'ready',skillPointsGranted:granted,expectedPublication:{state:{secretProgress:{completed:true,step:7},skills:{points:DISCRETE_MAXIMUM}}}});expect(commitAvocadoCommandV2(quote,source).accepted).toBe(true)}})

  test('rejects stale, replayed and hostile boundaries with zero getters',()=>{const state=stateWith({ip:'42'}),origin=publication(state,2),quote=quoteAvocadoCommandV2(origin,Object.freeze({kind:'feed-all',source:'infinity-points'}));expect(commitAvocadoCommandV2(quote,publication(state,3)).code).toBe('stale-publication');expect(commitAvocadoCommandV2(quote,origin).code).toBe('quote-rejected');let getters=0;const hostile=Object.defineProperty({},'kind',{enumerable:true,get(){getters+=1;return'feed-all'}}),throwing=new Proxy({},{ownKeys(){throw new Error('trap')},get(){getters+=1;throw new Error('getter')}});expect(quoteAvocadoCommandV2(origin,hostile as never).accepted).toBe(false);expect(()=>quoteAvocadoCommandV2(throwing as never,Object.freeze({kind:'feed-all',source:'infinity-points'}))).not.toThrow();expect(getters).toBe(0)})

  test('restricts Avocato V2 to its activated runtime and projection owners',()=>{const root=join(dirname(fileURLToPath(import.meta.url)),'..'),violations:string[]=[];for(const path of sourceFiles(root)){const normalized=path.replaceAll('\\','/');if(normalized.endsWith('/simulation/avocadoV2.ts')||normalized.endsWith('/simulation/avocadoV2.test.ts')||normalized.endsWith('/inspection/v2GameRuntime.ts')||relative(root,path).replaceAll('\\','/')==='game-state/numericFieldManifest.test.ts'||isExactFrontendProjectionPath(root,path))continue;for(const specifier of moduleSpecifiers(readFileSync(path,'utf8'),path))if(isModule(specifier))violations.push(`${relative(root,path)} -> ${specifier}`)}expect(violations).toEqual([]);for(const source of [`import * as a from './avocadoV2'`,`export * from './avocadoV2.mjs?raw#x'`,`void import(\`./avocadoV2.js\`)`,`const a=require('./avocadoV2.cjs#x')`,`import a = require('./avocadoV2.ts')`])expect(moduleSpecifiers(source,'hostile.ts').some(isModule),source).toBe(true)})
})

function sourceFiles(root:string):readonly string[]{const files:string[]=[],pending=[root];while(pending.length>0){const dir=pending.pop()!;for(const entry of readdirSync(dir,{withFileTypes:true})){const path=join(dir,entry.name);if(entry.isDirectory())pending.push(path);else if(!isExactStage6HarnessPath(root,path)&&/\.(?:ts|tsx|mts|cts|js|jsx|mjs|cjs)$/u.test(entry.name))files.push(path)}}return files}
function isExactStage6HarnessPath(root:string,path:string):boolean{return relative(join(root,'..'),path).replaceAll('\\','/')==='src/simulation/stage6V2EndToEnd.test.ts'}
function isExactFrontendProjectionPath(root:string,path:string):boolean{return relative(root,path).replaceAll('\\','/')==='inspection/frontendSnapshotV2.ts'}
function moduleSpecifiers(source:string,path:string):readonly string[]{const file=ts.createSourceFile(path,source,ts.ScriptTarget.Latest,true,/\.[jt]sx$/u.test(path)?ts.ScriptKind.TSX:ts.ScriptKind.TS),result:string[]=[];const add=(node:ts.Expression|undefined)=>{if(node!==undefined&&ts.isStringLiteralLike(node))result.push(node.text)};const visit=(node:ts.Node)=>{if(ts.isImportDeclaration(node)||ts.isExportDeclaration(node))add(node.moduleSpecifier);else if(ts.isImportEqualsDeclaration(node)&&ts.isExternalModuleReference(node.moduleReference))add(node.moduleReference.expression);else if(ts.isCallExpression(node)&&node.arguments.length===1&&(node.expression.kind===ts.SyntaxKind.ImportKeyword||(ts.isIdentifier(node.expression)&&node.expression.text==='require')))add(node.arguments[0]);ts.forEachChild(node,visit)};visit(file);return result}
function isModule(value:string):boolean{return /(?:^|\/)avocadoV2(?:\.[cm]?[jt]sx?|\/|$)/u.test(value.replace(/[?#].*$/u,''))}
test('Avocato guard exempts only the exact Stage 6 harness path',()=>{const root=join(dirname(fileURLToPath(import.meta.url)),'..');expect(isExactStage6HarnessPath(root,join(root,'simulation','stage6V2EndToEnd.test.ts'))).toBe(true);expect(isExactStage6HarnessPath(root,join(root,'hostile','stage6V2EndToEnd.test.ts'))).toBe(false)})
