import { readdirSync,readFileSync } from 'node:fs'
import { dirname,join,relative } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe,expect,test } from 'vitest'
import ts from 'typescript'
import { cloneCanonicalGameStateV2 } from '../game-state/cloneV2'
import { migratePreparedSaveToV2 } from '../game-state/mappingV2'
import type { CanonicalGameStateV2 } from '../game-state/typesV2'
import { gameDecimalFromCanonicalString,gameDecimalFromNumber,gameDecimalToCanonicalString } from '../math/gameDecimal'
import { PreparedSave } from '../save/prepare'
import { deserializeWebSave } from '../save/serialization'
import schema12Web from '../../test/fixtures/schema-12-canonical-idsweb1-first-run.txt?raw'
import { commitCanonicalQuantumResetV2,quoteCanonicalQuantumResetV2 } from './canonicalQuantumResetV2'

const migrated=migratePreparedSaveToV2(PreparedSave.fromDecoded(deserializeWebSave(schema12Web)),Object.freeze({kind:'trusted-same-device' as const})),base=migrated.state,runtime=migrated.runtime
const d=(value:string)=>value.includes('e')?gameDecimalFromCanonicalString(value):gameDecimalFromNumber(Number(value))
function stateWith(options:Readonly<{ip?:string;allocated?:string;available?:string;lifetime?:string;entangled?:boolean;secrets?:bigint;secretComplete?:boolean;artifact?:boolean}>= {}):CanonicalGameStateV2{return cloneCanonicalGameStateV2({...base,dyson:{...base.dyson,money:d('9'),science:d('8'),bots:d('7'),workers:d('6'),researchers:d('5'),goalStage:9n,totalPanelsDecayed:d('4')},infinity:{...base.infinity,availablePoints:d(options.ip??'42'),allocatedPoints:d(options.allocated??'11'),permanentSkillPoints:10n,secretsOfTheUniverse:17n},skills:{...base.skills,points:77n,fragments:0n,byId:{...base.skills.byId,banking:{...base.skills.byId.banking!,owned:true,timerSeconds:12},investmentPortfolio:{...base.skills.byId.investmentPortfolio!,owned:true,secondaryTimerSeconds:13}}},quantum:{...base.quantum,availableShards:d(options.available??'0'),lifetimeEarnedShards:d(options.lifetime??options.available??'0'),permanentSecrets:options.secrets??3n,unlocks:{...base.quantum.unlocks,quantumEntanglement:options.entangled??false}},secretProgress:{...base.secretProgress,completed:options.secretComplete??false},dream:{...base.dream,upgrades:{...base.dream.upgrades,translation1:options.artifact??false}},timeline:{...base.timeline,infinityCycleSeconds:123,dysonAutomationTargetIndex:7,researchAutomationTargetIndex:13}})}
const publication=(state:CanonicalGameStateV2,revision=1)=>Object.freeze({revision,state,runtime})

describe('Canonical Quantum reset V2',()=>{
  test('quotes and commits one ordinary leap from the pre-reset snapshot',()=>{const state=stateWith({artifact:true,secretComplete:true,secrets:3n}),source=publication(state,8),quote=quoteCanonicalQuantumResetV2(source,Object.freeze({kind:'quantum-action'}));expect(quote).toMatchObject({accepted:true,code:'ready',sourceRevision:8,operation:'ordinary-leap',resetSkillPoints:5n,expectedPublication:{revision:9}});expect(gameDecimalToCanonicalString(quote.requestedShards)).toBe('1e0');expect(gameDecimalToCanonicalString(quote.infinityPointsConsumed)).toBe('5.3e1');const commit=commitCanonicalQuantumResetV2(quote,source),next=commit.publication!.state;expect(commit).toMatchObject({accepted:true,changed:true,publication:{revision:9}});expect(gameDecimalToCanonicalString(next.quantum.availableShards)).toBe('1e0');expect(gameDecimalToCanonicalString(next.quantum.lifetimeEarnedShards)).toBe('1e0');for(const key of ['money','science','bots','workers','researchers','totalPanelsDecayed'] as const)expect(gameDecimalToCanonicalString(next.dyson[key])).toBe('0');expect(next.infinity).toMatchObject({inProgress:false,permanentSkillPoints:0n,secretsOfTheUniverse:3n,automationUnlocked:{bots:next.quantum.unlocks.automation,research:next.quantum.unlocks.automation}});expect(gameDecimalToCanonicalString(next.infinity.availablePoints)).toBe('0');expect(gameDecimalToCanonicalString(next.infinity.allocatedPoints)).toBe('0');expect(next.skills.points).toBe(5n);expect(next.skills.fragments).toBe(0n);expect(next.skills.byId.banking!.owned).toBe(false);expect(Object.values(next.research.levelsById).every(value=>typeof value==='bigint'?value===0n:gameDecimalToCanonicalString(value)==='0')).toBe(true);expect(next.statistics.currentQuantumRun.ordinaryInfinityCount).toBe(0n);expect(next.dream).toEqual(state.dream);expect(next.reality).toEqual(state.reality);expect(next.avocado).toEqual(state.avocado);expect(commit.publication!.runtime).not.toBe(runtime);expect(Object.isFrozen(commit.publication!.runtime.dysonEvaluationSnapshot)).toBe(true);expect(next.timeline.infinityBoundaryRemaining).toBeGreaterThan(0)})

  test('derives the reset Skill pool only from Reality artifacts and completed meditation four',()=>{const none=quoteCanonicalQuantumResetV2(publication(stateWith({secretComplete:false})),Object.freeze({kind:'quantum-action'})),meditation=quoteCanonicalQuantumResetV2(publication(stateWith({secretComplete:true})),Object.freeze({kind:'quantum-action'})),artifact=quoteCanonicalQuantumResetV2(publication(stateWith({artifact:true})),Object.freeze({kind:'quantum-action'}));expect(none.resetSkillPoints).toBe(0n);expect(meditation.resetSkillPoints).toBe(4n);expect(artifact.resetSkillPoints).toBe(1n)})

  test('autoassigns the retained mixed queue once and conserves the exact reset pool',()=>{const initial=stateWith({artifact:true,secretComplete:true}),state=cloneCanonicalGameStateV2({...initial,quantum:{...initial.quantum,unlocks:{...initial.quantum.unlocks,fragments:false}},skills:{...initial.skills,activeAutoAssignment:['startHereTree','fragmentAssembly','assemblyLineTree'],autoAssignNonRefundable:true}}),quote=quoteCanonicalQuantumResetV2(publication(state),Object.freeze({kind:'quantum-action'})),next=quote.expectedPublication!.state;expect(quote.resetSkillPoints).toBe(5n);expect(quote.autoAssignedSkillIds).toEqual(['startHereTree','assemblyLineTree']);expect(next.skills.byId.startHereTree!.owned).toBe(true);expect(next.skills.byId.assemblyLineTree!.owned).toBe(true);expect(next.skills.byId.fragmentAssembly!.owned).toBe(false);expect(next.skills.points+2n).toBe(quote.resetSkillPoints);expect(next.skills.byId.banking!.owned).toBe(false);expect(next.skills.byId.investmentPortfolio!.owned).toBe(false)})

  test('applies the independent legacy session Secrets rule',()=>{for(const [permanent,session] of [[0n,0n],[1n,0n],[2n,2n],[27n,27n]] as const){const quote=quoteCanonicalQuantumResetV2(publication(stateWith({secrets:permanent})),Object.freeze({kind:'quantum-action'}));expect(quote.expectedPublication!.state.infinity.secretsOfTheUniverse).toBe(session);expect(quote.expectedPublication!.state.quantum.permanentSecrets).toBe(permanent)}})

  test('entangles only available IP quotient/remainder and preserves every reset domain',()=>{const state=stateWith({ip:'100',available:'7',lifetime:'9',entangled:true}),source=publication(state,3),quote=quoteCanonicalQuantumResetV2(source,Object.freeze({kind:'quantum-action'}));expect(quote).toMatchObject({accepted:true,operation:'entanglement',resetSkillPoints:0n,autoAssignedSkillIds:[]});expect(gameDecimalToCanonicalString(quote.requestedShards)).toBe('2e0');expect(gameDecimalToCanonicalString(quote.infinityPointsConsumed)).toBe('8.4e1');const next=commitCanonicalQuantumResetV2(quote,source).publication!.state;expect(gameDecimalToCanonicalString(next.infinity.availablePoints)).toBe('1.6e1');expect(gameDecimalToCanonicalString(next.infinity.allocatedPoints)).toBe('1.1e1');expect(gameDecimalToCanonicalString(next.quantum.availableShards)).toBe('9e0');expect(gameDecimalToCanonicalString(next.quantum.lifetimeEarnedShards)).toBe('1.1e1');expect(next.dyson).toEqual(state.dyson);expect(next.skills).toEqual(state.skills);expect(next.dream).toEqual(state.dream)})

  test('handles huge integer Entanglement without narrowing and rejects invisible destination credit atomically',()=>{const huge=stateWith({ip:'4.2e1000',entangled:true}),quote=quoteCanonicalQuantumResetV2(publication(huge),Object.freeze({kind:'quantum-action'}));expect(quote.accepted).toBe(true);expect(quote.requestedShards.exponent).toBe(998);expect(quote.requestedShards.mantissa).toBeGreaterThan(9);expect(gameDecimalToCanonicalString(quote.expectedPublication!.state.infinity.availablePoints)).toBe('0');const saturated=stateWith({ip:'84',available:'1e1000',lifetime:'1e1000',entangled:true}),rejected=quoteCanonicalQuantumResetV2(publication(saturated),Object.freeze({kind:'quantum-action'}));expect(rejected).toMatchObject({accepted:false,code:'output-unrepresented',expectedPublication:null});expect(gameDecimalToCanonicalString(saturated.infinity.availablePoints)).toBe('8.4e1')})

  test('allows an ordinary reset whose one-Shard reward is unrepresented and reports both effective credits',()=>{const quote=quoteCanonicalQuantumResetV2(publication(stateWith({available:'1e1000',lifetime:'1e1000'})),Object.freeze({kind:'quantum-action'}));expect(quote.accepted).toBe(true);expect(gameDecimalToCanonicalString(quote.effectiveAvailableShards)).toBe('0');expect(gameDecimalToCanonicalString(quote.effectiveLifetimeShards)).toBe('0');expect(gameDecimalToCanonicalString(quote.expectedPublication!.state.quantum.availableShards)).toBe('1e1000')})

  test('reports a huge represented total IP wipe without narrowing',()=>{const quote=quoteCanonicalQuantumResetV2(publication(stateWith({ip:'1e1000',allocated:'1e1000'})),Object.freeze({kind:'quantum-action'}));expect(quote.accepted).toBe(true);expect(gameDecimalToCanonicalString(quote.infinityPointsConsumed)).toBe('2e1000');expect(gameDecimalToCanonicalString(quote.expectedPublication!.state.infinity.availablePoints)).toBe('0');expect(gameDecimalToCanonicalString(quote.expectedPublication!.state.infinity.allocatedPoints)).toBe('0')})

  test('derives the branch from owned Entanglement and gates ordinary on total IP',()=>{const ready=quoteCanonicalQuantumResetV2(publication(stateWith({ip:'31',allocated:'11'})),Object.freeze({kind:'quantum-action'}));expect(ready).toMatchObject({accepted:true,operation:'ordinary-leap'});expect(gameDecimalToCanonicalString(ready.infinityPointsConsumed)).toBe('4.2e1');expect(quoteCanonicalQuantumResetV2(publication(stateWith({ip:'30',allocated:'11'})),Object.freeze({kind:'quantum-action'})).code).toBe('not-ready');const entangled=quoteCanonicalQuantumResetV2(publication(stateWith({ip:'31',allocated:'11',entangled:true})),Object.freeze({kind:'quantum-action'}));expect(entangled).toMatchObject({accepted:false,operation:'entanglement',code:'not-ready'})})

  test('rejects not-ready, stale, replayed, exhausted and hostile inputs with zero getters',()=>{expect(quoteCanonicalQuantumResetV2(publication(stateWith({ip:'30',allocated:'11'})),Object.freeze({kind:'quantum-action'})).code).toBe('not-ready');expect(quoteCanonicalQuantumResetV2(publication(stateWith(),Number.MAX_SAFE_INTEGER),Object.freeze({kind:'quantum-action'})).code).toBe('revision-exhausted');const state=stateWith(),source=publication(state,4),quote=quoteCanonicalQuantumResetV2(source,Object.freeze({kind:'quantum-action'}));expect(commitCanonicalQuantumResetV2(quote,publication(state,5))).toMatchObject({accepted:false,code:'stale-publication',publication:null});expect(commitCanonicalQuantumResetV2(quote,source).code).toBe('quote-rejected');let getters=0;const accessor=Object.defineProperty({},'kind',{enumerable:true,get(){getters+=1;return'quantum-action'}}),throwing=new Proxy({},{ownKeys(){throw new Error('trap')},get(){getters+=1;throw new Error('getter')}});expect(quoteCanonicalQuantumResetV2(source,accessor as never).accepted).toBe(false);expect(()=>quoteCanonicalQuantumResetV2(throwing as never,Object.freeze({kind:'quantum-action'}))).not.toThrow();expect(getters).toBe(0)})

  test('accepts a canonical mutable/reordered reload snapshot but rejects unrelated same-revision drift',()=>{const state=stateWith(),source={runtime,state,revision:6},quote=quoteCanonicalQuantumResetV2(source,Object.freeze({kind:'quantum-action'}));expect(commitCanonicalQuantumResetV2(quote,{state:cloneCanonicalGameStateV2(state),revision:6,runtime}).accepted).toBe(true);const second=quoteCanonicalQuantumResetV2(source,Object.freeze({kind:'quantum-action'})),drift=cloneCanonicalGameStateV2({...state,meta:{...state.meta,tutorialComplete:!state.meta.tutorialComplete}});expect(commitCanonicalQuantumResetV2(second,publication(drift,6)).code).toBe('stale-publication')})

  test('restricts the Quantum reset owner to activated event, authority, runtime, and projection owners',()=>{const root=join(dirname(fileURLToPath(import.meta.url)),'..'),violations:string[]=[];for(const path of sourceFiles(root)){const normalized=path.replaceAll('\\','/');if(normalized.endsWith('/simulation/canonicalQuantumResetV2.ts')||normalized.endsWith('/simulation/canonicalQuantumResetV2.test.ts')||normalized.endsWith('/simulation/canonicalEventTimeModelV2.ts')||normalized.endsWith('/workers/storedTimeV2/storedTimeJobAuthorityV2.ts')||normalized.endsWith('/inspection/v2GameRuntime.ts')||isExactFrontendProjectionPath(root,path))continue;for(const specifier of moduleSpecifiers(readFileSync(path,'utf8'),path))if(isResetModule(specifier))violations.push(`${relative(root,path)} -> ${specifier}`)}expect(violations).toEqual([]);for(const source of [`import * as q from './canonicalQuantumResetV2'`,`export * from './canonicalQuantumResetV2.mjs?raw#x'`,`void import(\`./canonicalQuantumResetV2.js\`)`,`const q=require('./canonicalQuantumResetV2.cjs#x')`,`import q=require('./canonicalQuantumResetV2.ts')`])expect(moduleSpecifiers(source,'hostile.ts').some(isResetModule)).toBe(true)})
})

function sourceFiles(root:string):readonly string[]{const files:string[]=[],pending=[root];while(pending.length>0){const dir=pending.pop()!;for(const entry of readdirSync(dir,{withFileTypes:true})){const path=join(dir,entry.name);if(entry.isDirectory())pending.push(path);else if(!isExactStage6HarnessPath(root,path)&&/\.(?:ts|tsx|mts|cts|js|jsx|mjs|cjs)$/u.test(entry.name))files.push(path)}}return files}
function isExactStage6HarnessPath(root:string,path:string):boolean{return relative(join(root,'..'),path).replaceAll('\\','/')==='src/simulation/stage6V2EndToEnd.test.ts'}
function isExactFrontendProjectionPath(root:string,path:string):boolean{return relative(root,path).replaceAll('\\','/')==='inspection/frontendSnapshotV2.ts'}
function moduleSpecifiers(source:string,path:string):readonly string[]{const file=ts.createSourceFile(path,source,ts.ScriptTarget.Latest,true,/\.[jt]sx$/u.test(path)?ts.ScriptKind.TSX:ts.ScriptKind.TS),result:string[]=[];const add=(node:ts.Expression|undefined)=>{if(node!==undefined&&ts.isStringLiteralLike(node))result.push(node.text)};const visit=(node:ts.Node)=>{if(ts.isImportDeclaration(node)||ts.isExportDeclaration(node))add(node.moduleSpecifier);else if(ts.isImportEqualsDeclaration(node)&&ts.isExternalModuleReference(node.moduleReference))add(node.moduleReference.expression);else if(ts.isCallExpression(node)&&node.arguments.length===1&&(node.expression.kind===ts.SyntaxKind.ImportKeyword||(ts.isIdentifier(node.expression)&&node.expression.text==='require')))add(node.arguments[0]);ts.forEachChild(node,visit)};visit(file);return result}
function isResetModule(value:string):boolean{return /(?:^|\/)canonicalQuantumResetV2(?:\.[cm]?[jt]sx?|\/|$)/u.test(value.replace(/[?#].*$/u,''))}
test('Quantum reset guard exempts only the exact Stage 6 harness path',()=>{const root=join(dirname(fileURLToPath(import.meta.url)),'..');expect(isExactStage6HarnessPath(root,join(root,'simulation','stage6V2EndToEnd.test.ts'))).toBe(true);expect(isExactStage6HarnessPath(root,join(root,'hostile','stage6V2EndToEnd.test.ts'))).toBe(false)})
