import { describe,expect,test } from 'vitest'
import { readdirSync,readFileSync } from 'node:fs'
import { dirname,join,relative } from 'node:path'
import { fileURLToPath } from 'node:url'
import ts from 'typescript'
import { cloneCanonicalGameStateV2 } from '../game-state/cloneV2'
import { migratePreparedSaveToV2 } from '../game-state/mappingV2'
import type { CanonicalGameStateV2 } from '../game-state/typesV2'
import { gameDecimalFromCanonicalString,gameDecimalFromNumber,gameDecimalToCanonicalString } from '../math/gameDecimal'
import { PreparedSave } from '../save/prepare'
import { deserializeWebSave } from '../save/serialization'
import schema12Web from '../../test/fixtures/schema-12-canonical-idsweb1-first-run.txt?raw'
import { DISCRETE_MAXIMUM } from './numeric'
import { commitCanonicalDreamResetV2,commitPreparedCanonicalDreamResetV2,normalizeCanonicalFastDreamResetsV2,normalizePreparedCanonicalFastDreamResetsV2,quoteCanonicalDreamResetV2,quotePreparedCanonicalAutomaticDreamResetV2,registerCanonicalFastDreamNormalizationAuthorityV2ForWorker,registerCanonicalPreparedDreamResetAuthorityV2ForEventModel } from './canonicalDreamResetV2'
import { applyDreamUpgradeEffectsV2 } from './dreamV2'

const migrated=migratePreparedSaveToV2(PreparedSave.fromDecoded(deserializeWebSave(schema12Web)),Object.freeze({kind:'trusted-same-device' as const})),base=migrated.state,runtime=migrated.runtime
const d=(value:string)=>value.includes('e')?gameDecimalFromCanonicalString(value):gameDecimalFromNumber(Number(value))
function stateWith(options:Readonly<{stage?:bigint;resetCount?:bigint;strangeMatter?:string;resources?:Partial<CanonicalGameStateV2['dream']['resources']>;upgrades?:Partial<CanonicalGameStateV2['dream']['upgrades']>;huntersPerPurchase?:string;gatherersPerPurchase?:string}>= {}):CanonicalGameStateV2{return cloneCanonicalGameStateV2({...base,dream:{...base.dream,resetCount:options.resetCount??base.dream.resetCount,strangeMatter:d(options.strangeMatter??'0'),disasterStage:options.stage??base.dream.disasterStage,resources:{...base.dream.resources,...options.resources},upgrades:{...base.dream.upgrades,...options.upgrades},huntersPerPurchase:d(options.huntersPerPurchase??gameDecimalToCanonicalString(base.dream.huntersPerPurchase)),gatherersPerPurchase:d(options.gatherersPerPurchase??gameDecimalToCanonicalString(base.dream.gatherersPerPurchase))}})}
const publication=(state:CanonicalGameStateV2,revision=1)=>Object.freeze({revision,state,runtime})

describe('Canonical Dream reset V2',()=>{
  test.each([
    [1n,{cities:d('1')},'Meteor','1e0'],
    [2n,{bots:d('100')},'ArtificialIntelligence','1e1'],
    [3n,{spaceFactories:d('5')},'GlobalWarming','2e1'],
  ] as const)('authenticates automatic stage %s and records its effective reward',(_stage,resources,cause,reward)=>{const state=stateWith({stage:_stage,resources}),source=publication(state,4),quote=quoteCanonicalDreamResetV2(source,Object.freeze({kind:'automatic'}));expect(quote).toMatchObject({accepted:true,cause,sourceRevision:4,expectedPublication:{revision:5}});expect(gameDecimalToCanonicalString(quote.effectiveReward)).toBe(reward);const result=commitCanonicalDreamResetV2(quote,source);expect(result).toMatchObject({accepted:true,changed:true,publication:{revision:5}});expect(result.publication!.state.dream.resetCount).toBe(state.dream.resetCount+1n);expect(result.publication!.state.statistics.lastCompletedCycle.dreamCause).toBe(cause);expect(gameDecimalToCanonicalString(result.publication!.state.statistics.lastCompletedCycle.reward)).toBe(reward)})

  test('applies explicit Black Hole from captured swarm panels and resets every authored branch',()=>{const state=stateWith({resources:{hunters:d('99'),community:d('88'),swarmPanels:d('42'),railgunCharge:d('7')},upgrades:{hunter1:true,hunter4:true,mathematics3:true},huntersPerPurchase:'1e6',gatherersPerPurchase:'100'}),source=publication(state,8),points=state.skills.points,quote=quoteCanonicalDreamResetV2(source,Object.freeze({kind:'black-hole'})),result=commitCanonicalDreamResetV2(quote,source),next=result.publication!.state;expect(gameDecimalToCanonicalString(quote.requestedReward)).toBe('4.2e1');expect(next.dream.resetCount).toBe(state.dream.resetCount+1n);expect(gameDecimalToCanonicalString(next.dream.resources.hunters)).toBe('1e0');expect(gameDecimalToCanonicalString(next.dream.resources.community)).toBe('0');expect(gameDecimalToCanonicalString(next.dream.resources.railgunCharge)).toBe('0');expect(next.dream.railgun).toMatchObject({firing:false,fireProgress:0,shotsRemaining:0,activeRailguns:0,lastRoundsFired:0});expect(next.dream.education.mathematics.complete).toBe(true);expect(gameDecimalToCanonicalString(next.dream.parameters.solarPanelGeneration)).toBe('2e2');expect(gameDecimalToCanonicalString(next.dream.huntersPerPurchase)).toBe('1e3');expect(next.dream.upgrades).toEqual(state.dream.upgrades);expect(next.skills.points).toBe(points);expect(Object.isFrozen(result.publication!.runtime.dysonEvaluationSnapshot)).toBe(true);expect(result.publication!.runtime).not.toBe(runtime)})

  test('publishes a reset with zero effective SM/stat credit when a huge balance swallows the reward',()=>{const state=stateWith({stage:1n,strangeMatter:'1e1000',resources:{cities:d('1')}}),source=publication(state,2),quote=quoteCanonicalDreamResetV2(source,Object.freeze({kind:'automatic'}));expect(quote.accepted).toBe(true);expect(gameDecimalToCanonicalString(quote.requestedReward)).toBe('1e0');expect(gameDecimalToCanonicalString(quote.effectiveReward)).toBe('0');const result=commitCanonicalDreamResetV2(quote,source);expect(result.publication!.state.dream.resetCount).toBe(state.dream.resetCount+1n);expect(gameDecimalToCanonicalString(result.publication!.state.statistics.lastCompletedCycle.reward)).toBe('0')})

  test('keeps the issued prepared automatic reset byte-identical and one-use',()=>{const authority=registerCanonicalPreparedDreamResetAuthorityV2ForEventModel(),state=stateWith({stage:1n,resources:{cities:d('1')}}),source=publication(state,6),publicQuote=quoteCanonicalDreamResetV2(source,Object.freeze({kind:'automatic'})),publicCommit=commitCanonicalDreamResetV2(publicQuote,source),preparedQuote=quotePreparedCanonicalAutomaticDreamResetV2(authority,source);expect(preparedQuote).toMatchObject({accepted:true,cause:'Meteor',sourceRevision:6});expect(commitCanonicalDreamResetV2(preparedQuote,source).accepted).toBe(false);expect(commitPreparedCanonicalDreamResetV2(authority,publicQuote,source).accepted).toBe(false);expect(commitPreparedCanonicalDreamResetV2(authority,preparedQuote,Object.freeze({...source}))).toMatchObject({accepted:false,code:'stale-publication'});const secondQuote=quotePreparedCanonicalAutomaticDreamResetV2(authority,source),preparedCommit=commitPreparedCanonicalDreamResetV2(authority,secondQuote,source);expect(preparedCommit.publication).toEqual(publicCommit.publication);expect(commitPreparedCanonicalDreamResetV2(authority,secondQuote,source).accepted).toBe(false);expect(Object.isFrozen(preparedCommit.publication!.state.dream)).toBe(true);expect(Object.isFrozen(preparedCommit.publication!.state.statistics.minuteWindows)).toBe(true);let getters=0;const hostile=new Proxy({},{ownKeys(){throw new Error('trap')},get(){getters+=1;throw new Error('getter')}});expect(quotePreparedCanonicalAutomaticDreamResetV2(Object.freeze({owner:'canonical-event-time-v2'}),source).accepted).toBe(false);expect(quotePreparedCanonicalAutomaticDreamResetV2(authority,hostile as never).accepted).toBe(false);expect(getters).toBe(0)})

  test('keeps authored type-five assignment identical across direct purchase and reset replay',()=>{const source=stateWith({strangeMatter:'100',huntersPerPurchase:'1e6',upgrades:{hunter2:true}}),purchased=applyDreamUpgradeEffectsV2(source,'hunter4');expect(purchased).not.toBeNull();expect(gameDecimalToCanonicalString(purchased!.dream.huntersPerPurchase)).toBe('1e3');const resetSource=publication(cloneCanonicalGameStateV2({...purchased!,dream:{...purchased!.dream,resources:{...purchased!.dream.resources,swarmPanels:d('1')}}}),13),quote=quoteCanonicalDreamResetV2(resetSource,Object.freeze({kind:'black-hole'})),reset=commitCanonicalDreamResetV2(quote,resetSource);expect(gameDecimalToCanonicalString(reset.publication!.state.dream.huntersPerPurchase)).toBe('1e3')})

  test('applies one bounded Fast q-cycle reward and retained-window normalization',()=>{const authority=registerCanonicalFastDreamNormalizationAuthorityV2ForWorker(),state=stateWith({stage:1n,strangeMatter:'1e1000'}),result=normalizeCanonicalFastDreamResetsV2(authority,publication(state,9),Object.freeze({cycles:3n,cycleSeconds:10,firstCycleElapsedSeconds:10}));expect(result).toMatchObject({cause:'Meteor',resetCount:3n,publication:{revision:9}});expect(result.publication.state.dream.resetCount).toBe(state.dream.resetCount+3n);expect(gameDecimalToCanonicalString(result.requestedReward)).toBe('3e0');expect(gameDecimalToCanonicalString(result.effectiveReward)).toBe('0');expect(gameDecimalToCanonicalString(result.publication.state.dream.strangeMatter)).toBe('1e1000');expect(gameDecimalToCanonicalString(result.publication.state.statistics.lastCompletedCycle.reward)).toBe('0');for(const key of ['minuteWindows','halfHourWindows','dailyWindows'] as const)expect(result.publication.state.statistics[key].every(bucket=>gameDecimalToCanonicalString(bucket.strangeMatter)==='0')).toBe(true);expect(result.publication.state.statistics.minuteWindows[0]!.dreamResetCount).toBe(state.statistics.minuteWindows[0]!.dreamResetCount+3n);const represented=normalizeCanonicalFastDreamResetsV2(authority,publication(stateWith({stage:1n}),10),Object.freeze({cycles:3n,cycleSeconds:70,firstCycleElapsedSeconds:10}));expect(gameDecimalToCanonicalString(represented.effectiveReward)).toBe('3e0');for(const key of ['minuteWindows','halfHourWindows','dailyWindows'] as const)expect(represented.publication.state.statistics[key].map(bucket=>gameDecimalToCanonicalString(bucket.strangeMatter)).filter(value=>value!=='0')).toEqual(['3e0']);expect(()=>normalizeCanonicalFastDreamResetsV2(Object.freeze({policy:'stored-time-fast-v1'}),publication(state),Object.freeze({cycles:1n,cycleSeconds:10,firstCycleElapsedSeconds:10}))).toThrow(/authority/u);expect(()=>normalizeCanonicalFastDreamResetsV2(authority,publication(stateWith({stage:1n,resetCount:DISCRETE_MAXIMUM})),Object.freeze({cycles:1n,cycleSeconds:10,firstCycleElapsedSeconds:10}))).toThrow(/headroom/u)})

  test('keeps prepared Fast normalization byte-identical to the public boundary',()=>{const fast=registerCanonicalFastDreamNormalizationAuthorityV2ForWorker(),prepared=registerCanonicalPreparedDreamResetAuthorityV2ForEventModel(),source=publication(stateWith({stage:1n}),12),request=Object.freeze({cycles:7n,cycleSeconds:70,firstCycleElapsedSeconds:10}),publicResult=normalizeCanonicalFastDreamResetsV2(fast,source,request),preparedResult=normalizePreparedCanonicalFastDreamResetsV2(fast,prepared,source,request);expect(preparedResult).toEqual(publicResult);expect(Object.isFrozen(preparedResult.publication.state.statistics.dailyWindows)).toBe(true);expect(()=>normalizePreparedCanonicalFastDreamResetsV2(Object.freeze({policy:'stored-time-fast-v1'}),prepared,source,request)).toThrow(/authority/u);expect(()=>normalizePreparedCanonicalFastDreamResetsV2(fast,Object.freeze({owner:'canonical-event-time-v2'}),source,request)).toThrow(/authority/u)})

  test('retains every normalized reset when a minute sequence exceeds safe integer precision',()=>{const authority=registerCanonicalFastDreamNormalizationAuthorityV2ForWorker(),firstCycleElapsedSeconds=(2**53+8)*60,state=cloneCanonicalGameStateV2({...stateWith({stage:1n}),statistics:{...base.statistics,trackedSimulatedSeconds:firstCycleElapsedSeconds}}),result=normalizeCanonicalFastDreamResetsV2(authority,publication(state,11),Object.freeze({cycles:3n,cycleSeconds:128,firstCycleElapsedSeconds}));expect(result.publication.state.statistics.minuteWindows.reduce((total,bucket)=>total+bucket.dreamResetCount,0n)).toBe(3n);expect(result.publication.state.statistics.minuteWindows.some(bucket=>bucket.sequence>BigInt(Number.MAX_SAFE_INTEGER))).toBe(true)})

  test('fails closed for not-ready, saturated count and exhausted revision',()=>{expect(quoteCanonicalDreamResetV2(publication(stateWith({stage:1n}),1),Object.freeze({kind:'automatic'})).code).toBe('not-ready');expect(quoteCanonicalDreamResetV2(publication(stateWith({stage:1n,resetCount:DISCRETE_MAXIMUM,resources:{cities:d('1')}}),1),Object.freeze({kind:'automatic'})).code).toBe('reset-count-saturated');expect(quoteCanonicalDreamResetV2(publication(stateWith({stage:1n,resources:{cities:d('1')}}),Number.MAX_SAFE_INTEGER),Object.freeze({kind:'automatic'})).code).toBe('revision-exhausted')})

  test('rejects stale, replayed and hostile objects without returning attacker state',()=>{const state=stateWith({stage:1n,resources:{cities:d('1')}}),source=publication(state,7),quote=quoteCanonicalDreamResetV2(source,Object.freeze({kind:'automatic'}));expect(commitCanonicalDreamResetV2(quote,publication(state,8))).toMatchObject({accepted:false,code:'stale-publication',publication:null});expect(commitCanonicalDreamResetV2(quote,source)).toMatchObject({accepted:false,code:'quote-rejected',publication:null});let getters=0;const hostile=Object.defineProperty({},'kind',{enumerable:true,get(){getters+=1;return'automatic'}}),throwing=new Proxy({},{ownKeys(){throw new Error('trap')},get(){getters+=1;throw new Error('getter')}});expect(quoteCanonicalDreamResetV2(source,hostile as never).accepted).toBe(false);expect(()=>quoteCanonicalDreamResetV2(throwing as never,Object.freeze({kind:'automatic'}))).not.toThrow();expect(commitCanonicalDreamResetV2(null as never,throwing as never).publication).toBeNull();expect(getters).toBe(0)})
  test('restricts the reset owner to its activated event, runtime, and projection owners',()=>{const root=join(dirname(fileURLToPath(import.meta.url)),'..'),violations:string[]=[];for(const path of sourceFiles(root)){const normalized=path.replaceAll('\\','/');if(normalized.endsWith('/simulation/canonicalDreamResetV2.test.ts')||normalized.endsWith('/simulation/canonicalDreamResetV2.ts')||normalized.endsWith('/simulation/canonicalEventTimeModelV2.ts')||normalized.endsWith('/simulation/canonicalEventTimeModelV2.test.ts')||normalized.endsWith('/inspection/v2GameRuntime.ts')||relative(root,path).replaceAll('\\','/')==='game-state/numericFieldManifest.test.ts'||isExactFrontendProjectionPath(root,path))continue;for(const specifier of moduleSpecifiers(readFileSync(path,'utf8'),path))if(isResetModule(specifier))violations.push(`${relative(root,path)} -> ${specifier}`)}expect(violations).toEqual([]);for(const source of [`import * as r from './canonicalDreamResetV2'`,`export * from './canonicalDreamResetV2.mjs?raw#x'`,`void import(\`./canonicalDreamResetV2.js\`)`,`const r=require('./canonicalDreamResetV2.cjs#x')`,`import r=require('./canonicalDreamResetV2.ts')`])expect(moduleSpecifiers(source,'hostile.ts').some(isResetModule)).toBe(true)})
})

function sourceFiles(root:string):readonly string[]{const files:string[]=[],pending=[root];while(pending.length>0){const dir=pending.pop()!;for(const entry of readdirSync(dir,{withFileTypes:true})){const path=join(dir,entry.name);if(entry.isDirectory())pending.push(path);else if(!isExactStage6HarnessPath(root,path)&&/\.(?:ts|tsx|mts|cts|js|jsx|mjs|cjs)$/u.test(entry.name))files.push(path)}}return files}
function isExactStage6HarnessPath(root:string,path:string):boolean{return relative(join(root,'..'),path).replaceAll('\\','/')==='src/simulation/stage6V2EndToEnd.test.ts'}
function isExactFrontendProjectionPath(root:string,path:string):boolean{return relative(root,path).replaceAll('\\','/')==='inspection/frontendSnapshotV2.ts'}
function moduleSpecifiers(source:string,path:string):readonly string[]{const file=ts.createSourceFile(path,source,ts.ScriptTarget.Latest,true,/\.[jt]sx$/u.test(path)?ts.ScriptKind.TSX:ts.ScriptKind.TS),result:string[]=[];const add=(node:ts.Expression|undefined)=>{if(node!==undefined&&ts.isStringLiteralLike(node))result.push(node.text)};const visit=(node:ts.Node)=>{if(ts.isImportDeclaration(node)||ts.isExportDeclaration(node))add(node.moduleSpecifier);else if(ts.isImportEqualsDeclaration(node)&&ts.isExternalModuleReference(node.moduleReference))add(node.moduleReference.expression);else if(ts.isCallExpression(node)&&node.arguments.length===1&&(node.expression.kind===ts.SyntaxKind.ImportKeyword||(ts.isIdentifier(node.expression)&&node.expression.text==='require')))add(node.arguments[0]);ts.forEachChild(node,visit)};visit(file);return result}
function isResetModule(value:string):boolean{return /(?:^|\/)canonicalDreamResetV2(?:\.[cm]?[jt]sx?|\/|$)/u.test(value.replace(/[?#].*$/u,''))}
test('Dream reset guard exempts only the exact Stage 6 harness path',()=>{const root=join(dirname(fileURLToPath(import.meta.url)),'..');expect(isExactStage6HarnessPath(root,join(root,'simulation','stage6V2EndToEnd.test.ts'))).toBe(true);expect(isExactStage6HarnessPath(root,join(root,'hostile','stage6V2EndToEnd.test.ts'))).toBe(false)})
