import { getGameAssetsByKind } from '../game-data/catalog'
import { integerGameDecimalFromNumber, type GameDecimal } from '../math/gameDecimal'

export const DREAM_V2_UPGRADE_KIND = 'IdleDysonSwarm.Data.Balance.SimulationUpgradeDefinition'
const EXPECTED = Object.freeze({
  advancedPhysics1:'92|mathematics1:1|0:advancedPhysics1:1:0,4:advancedPhysicsResearchTime:1:3600', advancedPhysics2:'126|advancedPhysics1:1|0:advancedPhysics2:1:0,4:advancedPhysicsResearchTime:1:1800', advancedPhysics3:'381|advancedPhysics2:1|0:advancedPhysics3:1:0,4:advancedPhysicsResearchTime:1:600', advancedPhysics4:'654|advancedPhysics3:1|0:advancedPhysics4:1:0,3:advancedPhysicsComplete:1:0',
  bots1:'211|counterAi:1|0:bots1:1:0,0:botsBoost1Activator:1:0', bots2:'1111|bots1:1|0:bots2:1:0,0:botsBoost2Activator:1:0', citiesBoost:'1337|counterMeteor:1|0:citiesBoost:1:0,0:citiesBoostActivator:1:0', counterAi:'42|counterMeteor:1|0:counterAi:1:0,8:disasterStage:1:3', counterGw:'128|counterAi:1|0:counterGw:1:0,8:disasterStage:1:42', counterMeteor:'4||0:counterMeteor:1:0,8:disasterStage:1:2',
  engineering1:'2|counterMeteor:1|0:engineering1:1:0,4:engineeringResearchTime:1:300', engineering2:'10|engineering1:1|0:engineering2:1:0,4:engineeringResearchTime:1:60', engineering3:'42|engineering2:1|0:engineering3:1:0,3:engineeringComplete:1:0', factoriesBoost:'21|counterAi:1|0:factoriesBoost:1:0,0:factoriesBoostActivator:1:0',
  gatherer1:'2||0:gatherer1:1:0,6:gatherers:1:1', gatherer2:'20|gatherer1:1|0:gatherer2:1:0,6:gatherers:1:10', gatherer3:'40|gatherer2:1|0:gatherer3:1:0,6:gatherers:1:1000', gatherer4:'40|gatherer2:1|0:gatherer4:1:0,5:gatherersPerPurchase:1:1000', hunter1:'2||0:hunter1:1:0,6:hunters:1:1', hunter2:'20|hunter1:1|0:hunter2:1:0,6:hunters:1:10', hunter3:'40|hunter2:1|0:hunter3:1:0,6:hunters:1:1000', hunter4:'40|hunter2:1|0:hunter4:1:0,5:huntersPerPurchase:1:1000',
  mathematics1:'44|counterAi:1|0:mathematics1:1:0,4:mathematicsResearchTime:1:1800', mathematics2:'88|mathematics1:1|0:mathematics2:1:0,4:mathematicsResearchTime:1:600', mathematics3:'124|mathematics2:1|0:mathematics3:1:0,3:mathematicsComplete:1:0,6:solarPanelGeneration:1:200',
  railguns1:'1221|counterGw:1|0:railguns1:1:0,0:railgunActivator1:1:0', railguns2:'12221|railguns1:1|0:railguns2:1:0,0:railgunActivator2:1:0', rockets1:'1111|counterGw:1|0:rockets1:1:0,4:rocketsPerSpaceFactory:1:5', rockets2:'2222|rockets1:1|0:rockets2:1:0,4:rocketsPerSpaceFactory:1:3', rockets3:'3333|rockets2:1|0:rockets3:1:0,4:rocketsPerSpaceFactory:1:1', sfacs1:'1221|counterGw:1|0:sfacs1:1:0,0:sfActivator1:1:0', sfacs2:'12221|sfacs1:1|0:sfacs2:1:0,0:sfActivator2:1:0', sfacs3:'122221|sfacs2:1|0:sfacs3:1:0,0:sfActivator3:1:0',
  shipping1:'18|engineering1:1|0:shipping1:1:0,4:shippingResearchTime:1:600', shipping2:'27|shipping1:1|0:shipping2:1:0,3:shippingComplete:1:0', workerBoost:'42||0:workerBoost:1:0,0:workerBoostAcivator:1:0', worldPeace1:'52|worldTrade1:1|0:worldPeace1:1:0,4:worldPeaceResearchTime:1:3600', worldPeace2:'74|worldPeace1:1|0:worldPeace2:1:0,4:worldPeaceResearchTime:1:1800', worldPeace3:'188|worldPeace2:1|0:worldPeace3:1:0,4:worldPeaceResearchTime:1:600', worldPeace4:'324|worldPeace3:1|0:worldPeace4:1:0,3:worldPeaceComplete:1:0', worldTrade1:'44|shipping1:1|0:worldTrade1:1:0,4:worldTradeResearchTime:1:1800', worldTrade2:'88|worldTrade1:1|0:worldTrade2:1:0,4:worldTradeResearchTime:1:600', worldTrade3:'124|worldTrade2:1|0:worldTrade3:1:0,3:worldTradeComplete:1:0',
} as const)
export const DREAM_V2_UPGRADE_IDS = Object.freeze(Object.keys(EXPECTED) as DreamUpgradeIdV2[])
export type DreamUpgradeIdV2 = keyof typeof EXPECTED

export interface DreamUpgradeEffectV2 { readonly effectType:number; readonly targetKey:string; readonly boolValue:boolean; readonly numericValue:number }
export interface DreamUpgradeDefinitionV2 { readonly id:DreamUpgradeIdV2; readonly cost:GameDecimal; readonly prerequisites:readonly {readonly key:DreamUpgradeIdV2;readonly mustBeOwned:boolean}[]; readonly effects:readonly DreamUpgradeEffectV2[] }

export function compileDreamCatalogV2(input:unknown=getGameAssetsByKind(DREAM_V2_UPGRADE_KIND)):Readonly<Record<DreamUpgradeIdV2,DreamUpgradeDefinitionV2>> {
  const all=closedArray(input,'Dream catalog assets'); const layer=[] as unknown[]
  for(const asset of all){ const env=closedObject(asset,['id','kind','data'],'Dream asset'); if(env.kind!==DREAM_V2_UPGRADE_KIND) continue; const preliminary=closedObject(env.data,['cost','key','layer','prerequisites','purchaseEffects'],`Dream ${String(env.id)} data`); if(preliminary.layer===0) layer.push(Object.freeze({env,preliminary})) }
  if(layer.length!==43) throw new Error('Dream V2 catalog must contain exactly 43 layer-zero definitions.')
  const entries: [DreamUpgradeIdV2,DreamUpgradeDefinitionV2][]=[]; const seen=new Set<string>()
  for(const item of layer){ const pair=item as {env:Readonly<Record<string,unknown>>;preliminary:Readonly<Record<string,unknown>>}; const id=pair.env.id; const data=pair.preliminary
    if(typeof id!=='string'||!(id in EXPECTED)||data.key!==id||seen.has(id)) throw new Error('Dream V2 definition identity mismatch.')
    const prerequisites=closedArray(data.prerequisites,`${id}.prerequisites`).map((value,index)=>{const p=closedObject(value,['key','mustBeOwned'],`${id}.prerequisites[${index}]`);if(typeof p.key!=='string'||!(p.key in EXPECTED)||(p.mustBeOwned!==0&&p.mustBeOwned!==1))throw new Error('Dream prerequisite mismatch.');return Object.freeze({key:p.key as DreamUpgradeIdV2,mustBeOwned:p.mustBeOwned===1})})
    const effects=closedArray(data.purchaseEffects,`${id}.purchaseEffects`).map((value,index)=>{const e=closedObject(value,['boolValue','effectType','numericValue','targetKey'],`${id}.purchaseEffects[${index}]`);if((e.boolValue!==0&&e.boolValue!==1)||typeof e.effectType!=='number'||!Number.isSafeInteger(e.effectType)||typeof e.numericValue!=='number'||!Number.isFinite(e.numericValue)||Object.is(e.numericValue,-0)||typeof e.targetKey!=='string')throw new Error('Dream effect mismatch.');return Object.freeze({boolValue:e.boolValue===1,effectType:e.effectType,targetKey:e.targetKey,numericValue:e.numericValue})})
    if(typeof data.cost!=='number'||!Number.isSafeInteger(data.cost)||data.cost<0||Object.is(data.cost,-0)||signature(data.cost,prerequisites,effects)!==EXPECTED[id as DreamUpgradeIdV2])throw new Error(`Dream V2 authored contract mismatch for ${id}.`)
    seen.add(id);entries.push([id as DreamUpgradeIdV2,Object.freeze({id:id as DreamUpgradeIdV2,cost:integerGameDecimalFromNumber(data.cost),prerequisites:Object.freeze(prerequisites),effects:Object.freeze(effects)})]) }
  if(seen.size!==43)throw new Error('Dream V2 catalog is incomplete.'); return Object.freeze(Object.fromEntries(entries)) as Readonly<Record<DreamUpgradeIdV2,DreamUpgradeDefinitionV2>>
}
export function validateDreamCatalogV2(input:unknown):boolean{try{compileDreamCatalogV2(input);return true}catch{return false}}
function signature(cost:number,p:readonly {key:string;mustBeOwned:boolean}[],e:readonly DreamUpgradeEffectV2[]):string{return `${cost}|${p.map(x=>`${x.key}:${x.mustBeOwned?1:0}`).join(',')}|${e.map(x=>`${x.effectType}:${x.targetKey}:${x.boolValue?1:0}:${x.numericValue}`).join(',')}`}
function closedArray(value:unknown,path:string):readonly unknown[]{if(!Array.isArray(value)||Object.getPrototypeOf(value)!==Array.prototype)throw new Error(`${path} must be an ordinary array.`);const d=Object.getOwnPropertyDescriptors(value);const length=Object.getOwnPropertyDescriptor(value,'length');if(Reflect.ownKeys(d).length!==value.length+1||length===undefined||!('value'in length)||length.value!==value.length||length.enumerable||Array.from({length:value.length},(_,i)=>d[String(i)]).some(x=>x===undefined||!x.enumerable||!('value'in x)))throw new Error(`${path} must be dense data.`);return Array.from({length:value.length},(_,i)=>d[String(i)]!.value)}
function closedObject(value:unknown,keys:readonly string[],path:string):Readonly<Record<string,unknown>>{if(value===null||typeof value!=='object'||Array.isArray(value)||Object.getPrototypeOf(value)!==Object.prototype)throw new Error(`${path} must be ordinary.`);const d=Object.getOwnPropertyDescriptors(value);const actual=Reflect.ownKeys(d);if(actual.length!==keys.length||actual.some(k=>typeof k!=='string'||!keys.includes(k))||keys.some(k=>d[k]===undefined||!d[k]!.enumerable||!('value'in d[k]!)))throw new Error(`${path} must be closed data.`);return Object.freeze(Object.fromEntries(keys.map(k=>[k,d[k]!.value])))}
export const DREAM_V2_CATALOG=compileDreamCatalogV2()
