import { readdirSync,readFileSync } from 'node:fs'
import { dirname,join,relative } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe,expect,test } from 'vitest'
import ts from 'typescript'
import { getGameAssetsByKind } from '../game-data/catalog'
import { cloneCanonicalGameStateV2 } from '../game-state/cloneV2'
import { migratePreparedSaveToV2 } from '../game-state/mappingV2'
import type { CanonicalGameStateV2 } from '../game-state/typesV2'
import { GAME_DECIMAL_ONE, addGameDecimals, gameDecimalFromCanonicalString, gameDecimalFromNumber, gameDecimalToCanonicalString, subtractGameDecimals } from '../math/gameDecimal'
import { PreparedSave } from '../save/prepare'
import { deserializeWebSave } from '../save/serialization'
import schema12Web from '../../test/fixtures/schema-12-canonical-idsweb1-first-run.txt?raw'
import { commitDreamCommandV2,quoteDreamCommandV2 } from '../application/dreamStrangeMatterAuthorityV2'
import { DREAM_V2_CATALOG,DREAM_V2_UPGRADE_IDS,DREAM_V2_UPGRADE_KIND,validateDreamCatalogV2 } from './dreamCatalogV2'
import { advanceDreamEducationV2,advanceDreamFoundationalV2,advanceDreamRailgunV2,advanceDreamSpaceAgeV2,deriveDreamV2PresentationFacts,prepareCanonicalDreamKernelStateV2,previewDreamInfluencePurchaseModesV2,purchaseDreamInfluenceV2,registerCanonicalDreamKernelAuthorityV2ForEventModel,runDreamConversionsV2 } from './dreamV2'
import { advanceV2TimeResourceSlice } from './timeResourcesV2'

const migrated=migratePreparedSaveToV2(PreparedSave.fromDecoded(deserializeWebSave(schema12Web)),Object.freeze({kind:'trusted-same-device' as const}))
const base=migrated.state
const runtime=migrated.runtime
const d=(value:string)=>value.includes('e')?gameDecimalFromCanonicalString(value):gameDecimalFromNumber(Number(value))
function stateWith(options:Readonly<{resources?:Partial<CanonicalGameStateV2['dream']['resources']>;parameters?:Partial<CanonicalGameStateV2['dream']['parameters']>;timers?:Partial<CanonicalGameStateV2['dream']['timers']>;education?:Partial<CanonicalGameStateV2['dream']['education']>;upgrades?:Partial<CanonicalGameStateV2['dream']['upgrades']>;doubleTime?:Partial<CanonicalGameStateV2['timeline']['doubleTime']>;influence?:string;strangeMatter?:string;railgun?:Partial<CanonicalGameStateV2['dream']['railgun']>}>= {}):CanonicalGameStateV2{
  return cloneCanonicalGameStateV2({...base,timeline:{...base.timeline,doubleTime:{...base.timeline.doubleTime,...options.doubleTime}},reality:{...base.reality,influence:d(options.influence??'0')},dream:{...base.dream,strangeMatter:d(options.strangeMatter??'0'),resources:{...base.dream.resources,...options.resources},parameters:{...base.dream.parameters,...options.parameters},timers:{...base.dream.timers,...options.timers},education:{...base.dream.education,...options.education},upgrades:{...base.dream.upgrades,...options.upgrades},railgun:{...base.dream.railgun,...options.railgun}}})
}

describe('Dream V2 catalog and kernels',()=>{
  test('derives no-time presentation rates from the exact kernel formulas at extreme scale',()=>{
    const ordinary=stateWith({resources:{hunters:d('1'),solarPanels:d('2')},parameters:{solarPanelGeneration:d('3')}})
    const facts=deriveDreamV2PresentationFacts(ordinary,GAME_DECIMAL_ONE)
    expect(gameDecimalToCanonicalString(facts.foundationalInformation.production.timers.hunterTimerProgress.progressPerSecond)).toBe('1e0')
    expect(gameDecimalToCanonicalString(facts.spaceAge.production.energy.solarPerSecond)).toBe('6e0')
    expect(advanceDreamFoundationalV2(ordinary,3,GAME_DECIMAL_ONE).produced.community).toEqual(d('1'))
    const huge=deriveDreamV2PresentationFacts(stateWith({resources:{hunters:d('1e1000'),spaceFactories:d('1e1000')}}),GAME_DECIMAL_ONE)
    expect(gameDecimalToCanonicalString(huge.foundationalInformation.production.timers.hunterTimerProgress.progressPerSecond)).toBe('1.001e3')
    expect(huge.spaceAge.production.spaceFactory.progressPerSecond.exponent).toBeGreaterThanOrEqual(3)
  })
  test('closes all 43 authored layer-zero definitions and rejects drift/accessors',()=>{
    expect(DREAM_V2_UPGRADE_IDS).toHaveLength(43);expect(Object.keys(DREAM_V2_CATALOG)).toHaveLength(43);expect(gameDecimalToCanonicalString(DREAM_V2_CATALOG.counterMeteor.cost)).toBe('4e0')
    const assets=getGameAssetsByKind(DREAM_V2_UPGRADE_KIND);expect(validateDreamCatalogV2(assets)).toBe(true)
    expect(validateDreamCatalogV2(assets.map((asset,index)=>index===0?{...asset,data:{...asset.data,cost:999}}:asset))).toBe(false)
    let getters=0;const hostile=Object.defineProperty({},'id',{enumerable:true,get(){getters+=1;return 'x'}});expect(validateDreamCatalogV2([hostile,...assets.slice(1)])).toBe(false);expect(getters).toBe(0)
  })
  test('captures every foundational producer at tick start',()=>{
    const source=stateWith({resources:{hunters:d('1'),community:d('0'),housing:d('0')},timers:{hunterTimerProgress:0,communityTimerProgress:0}})
    const first=advanceDreamFoundationalV2(source,3,GAME_DECIMAL_ONE);expect(first.accepted).toBe(true);expect(gameDecimalToCanonicalString(first.state.dream.resources.community)).toBe('1e0');expect(gameDecimalToCanonicalString(first.state.dream.resources.housing)).toBe('0')
    const second=advanceDreamFoundationalV2(first.state,3,GAME_DECIMAL_ONE);expect(gameDecimalToCanonicalString(second.state.dream.resources.housing)).toBe('1e0');expect(source.dream.resources.community).toEqual(d('0'))
  })
  test('reports requested and represented foundational arrivals independently',()=>{const source=stateWith({resources:{bots:d('1'),rockets:d('1e1000')},timers:{botsTimerProgress:0}});const result=advanceDreamFoundationalV2(source,2000,GAME_DECIMAL_ONE);expect(gameDecimalToCanonicalString(result.requested.rockets)).toBe('1e0');expect(gameDecimalToCanonicalString(result.produced.rockets)).toBe('0');expect(result.changed).toBe(false);expect(result.state).toBe(source)})
  test('corrects an upstream quotient that rounds above a repeated fractional timer total',()=>{let state=stateWith({resources:{hunters:d('1')}});for(let index=0;index<16;index+=1){const result=advanceDreamFoundationalV2(state,.1,GAME_DECIMAL_ONE);expect(result.accepted).toBe(true);state=result.state}expect(state.dream.timers.hunterTimerProgress).toBeGreaterThanOrEqual(0);expect(state.dream.timers.hunterTimerProgress).toBeLessThan(3)})
  test('requires a canonical split at boost expiry and permits immediate sub-ten-second reactivation',()=>{const boosted=stateWith({resources:{hunters:d('1')},parameters:{communityBoostClock:2,communityBoostDuration:3,communityBoostIsFree:true}});expect(advanceDreamFoundationalV2(boosted,3,GAME_DECIMAL_ONE).accepted).toBe(false);const boundary=advanceDreamFoundationalV2(boosted,2,GAME_DECIMAL_ONE);expect(boundary.accepted).toBe(true);expect(boundary.state.dream.parameters.communityBoostClock).toBe(0);const publication=Object.freeze({revision:3,state:boundary.state,runtime});const quote=quoteDreamCommandV2(publication,Object.freeze({kind:'boost' as const,boostId:'community' as const}));const committed=commitDreamCommandV2(quote,publication);expect(committed).toMatchObject({accepted:true,changed:true,publication:{revision:4,state:{dream:{parameters:{communityBoostClock:3}}}}})})
  test('runs housing, village, then bulk rocket conversions sequentially without minting',()=>{
    const source=stateWith({resources:{housing:d('10'),villages:d('24'),cities:d('0'),rockets:d('100'),factories:d('100'),spaceFactories:d('0')},parameters:{rocketsPerSpaceFactory:d('1')}})
    const result=runDreamConversionsV2(source);expect(result.changed).toBe(true);expect(gameDecimalToCanonicalString(result.housingToVillages)).toBe('1e0');expect(gameDecimalToCanonicalString(result.villagesToCities)).toBe('1e0');expect(gameDecimalToCanonicalString(result.rocketsToSpaceFactories)).toBe('1e2');expect(gameDecimalToCanonicalString(result.state.dream.resources.spaceFactories)).toBe('1e2');expect(gameDecimalToCanonicalString(result.state.dream.resources.rockets)).toBe('0');expect(gameDecimalToCanonicalString(result.state.dream.resources.factories)).toBe('0')
  })
  test('advances all education in Decimal space and applies Mathematics parity',()=>{
    const subject={...base.dream.education.mathematics,active:true,complete:false,progress:d('1e1000'),researchTime:10,cost:d('1')};const source=stateWith({education:{mathematics:subject},parameters:{solarPanelGeneration:d('1')}});const result=advanceDreamEducationV2(source,1,GAME_DECIMAL_ONE);expect(result.completed).toEqual(['mathematics']);expect(result.state.dream.education.mathematics.complete).toBe(true);expect(gameDecimalToCanonicalString(result.state.dream.education.mathematics.progress)).toBe('1e1000');expect(gameDecimalToCanonicalString(result.state.dream.parameters.solarPanelGeneration)).toBe('2e2')
  })
  test('captures Space Age rates before arrivals and preserves represented energy debit/credit',()=>{
    const source=stateWith({resources:{solarPanels:d('1'),energy:d('10'),spaceFactories:d('1'),dysonPanels:d('0')},parameters:{solarPanelGeneration:d('2'),railgunMaxCharge:d('1')}});const result=advanceDreamSpaceAgeV2(source,2,GAME_DECIMAL_ONE);expect(result.accepted).toBe(true);expect(gameDecimalToCanonicalString(result.energyGenerated)).toBe('4e0');expect(gameDecimalToCanonicalString(result.state.dream.resources.dysonPanels)).toBe('2e0');expect(source.dream.resources.dysonPanels).toEqual(d('0'))
  })
  test('keeps prepared continuous phases and their combined order byte-identical',()=>{const source=stateWith({resources:{hunters:d('1'),solarPanels:d('1'),spaceFactories:d('1'),energy:d('10')},parameters:{solarPanelGeneration:d('2'),railgunMaxCharge:d('1')},education:{engineering:{...base.dream.education.engineering,active:true,complete:false,progress:d('0'),researchTime:1,cost:d('1')}}}),authority=registerCanonicalDreamKernelAuthorityV2ForEventModel(),prepared=prepareCanonicalDreamKernelStateV2(authority,cloneCanonicalGameStateV2(source)),publicSpace=advanceDreamSpaceAgeV2(source,1,GAME_DECIMAL_ONE),preparedSpace=advanceDreamSpaceAgeV2(prepared,1,GAME_DECIMAL_ONE),publicFoundational=advanceDreamFoundationalV2(cloneCanonicalGameStateV2(source),1,GAME_DECIMAL_ONE),preparedFoundational=advanceDreamFoundationalV2(prepareCanonicalDreamKernelStateV2(authority,cloneCanonicalGameStateV2(source)),1,GAME_DECIMAL_ONE),publicEducation=advanceDreamEducationV2(cloneCanonicalGameStateV2(source),1,GAME_DECIMAL_ONE),preparedEducation=advanceDreamEducationV2(prepareCanonicalDreamKernelStateV2(authority,cloneCanonicalGameStateV2(source)),1,GAME_DECIMAL_ONE);expect(preparedSpace).toEqual(publicSpace);expect(preparedFoundational).toEqual(publicFoundational);expect(preparedEducation).toEqual(publicEducation);const publicCombined=advanceDreamEducationV2(advanceDreamFoundationalV2(publicSpace.state,1,GAME_DECIMAL_ONE).state,1,GAME_DECIMAL_ONE),preparedCombined=advanceDreamEducationV2(advanceDreamFoundationalV2(preparedSpace.state,1,GAME_DECIMAL_ONE).state,1,GAME_DECIMAL_ONE);expect(preparedCombined).toEqual(publicCombined);expect(preparedCombined.state).not.toBe(prepared);expect(Object.isFrozen(preparedCombined.state.dream.resources)).toBe(true);expect(gameDecimalToCanonicalString(prepared.dream.resources.community)).toBe('0')})
  test('reports represented Space Age energy and derives a zero-production payload from sustainable energy',()=>{const noCredit=stateWith({resources:{solarPanels:d('1'),energy:d('1e1000')},parameters:{solarPanelGeneration:d('1')}});expect(gameDecimalToCanonicalString(advanceDreamSpaceAgeV2(noCredit,1,GAME_DECIMAL_ONE).energyGenerated)).toBe('0');const payload=stateWith({resources:{solarPanels:d('100'),energy:d('100'),railgunCharge:d('0'),dysonPanels:d('1000'),swarmPanels:d('0'),spaceFactories:d('0')},parameters:{solarPanelGeneration:d('1'),railgunMaxCharge:d('1')}});const fired=advanceDreamRailgunV2(payload,.1,GAME_DECIMAL_ONE);expect(fired.roundsFired).toBe(1);expect(gameDecimalToCanonicalString(fired.panelsLaunched)).toBe('1e2')})
  test('moves railgun escrow atomically without energy or panel minting',()=>{
    const source=stateWith({resources:{energy:d('10'),railgunCharge:d('0'),dysonPanels:d('10'),swarmPanels:d('0')},parameters:{railgunMaxCharge:d('1')},railgun:{firing:false,fireProgress:0,shotsRemaining:0,activeRailguns:0,reservedPanels:d('0')}});const beforeEnergy=addGameDecimals(source.dream.resources.energy,source.dream.resources.railgunCharge);const result=advanceDreamRailgunV2(source,.1,GAME_DECIMAL_ONE);expect(result).toMatchObject({accepted:true,changed:true,roundsFired:1});expect(gameDecimalToCanonicalString(subtractGameDecimals(beforeEnergy,addGameDecimals(result.state.dream.resources.energy,result.state.dream.resources.railgunCharge)))).toBe('1e-1');expect(gameDecimalToCanonicalString(addGameDecimals(addGameDecimals(result.state.dream.resources.dysonPanels,result.state.dream.railgun.reservedPanels),result.state.dream.resources.swarmPanels))).toBe('1e1')
  })
  test('reports charge refunds as zero positive transfer',()=>{const source=stateWith({resources:{energy:d('0'),railgunCharge:d('10'),dysonPanels:d('10'),swarmPanels:d('0')},parameters:{railgunMaxCharge:d('1')},railgun:{firing:false,fireProgress:0,shotsRemaining:0,activeRailguns:0,reservedPanels:d('0')}});const result=advanceDreamRailgunV2(source,.1,GAME_DECIMAL_ONE);expect(gameDecimalToCanonicalString(result.chargeTransferred)).toBe('0');expect(gameDecimalToCanonicalString(result.state.dream.resources.energy)).toBe('9e0')})
  test('settles multiple authored railgun volleys within one accelerated boundary',()=>{const source=stateWith({doubleTime:{unlocked:true,enabled:true,bankSeconds:10,rate:1},resources:{energy:d('1000'),railgunCharge:d('0'),dysonPanels:d('1000'),swarmPanels:d('0'),spaceFactories:d('1')},parameters:{railgunMaxCharge:d('1')},railgun:{firing:false,fireProgress:0,shotsRemaining:0,activeRailguns:0,reservedPanels:d('0')}});const result=advanceDreamRailgunV2(source,1,gameDecimalFromNumber(2));expect(result.accepted).toBe(true);expect(result.roundsFired).toBe(20);expect(result.state.dream.railgun.lastRoundsFired).toBe(20);expect(gameDecimalToCanonicalString(result.panelsLaunched)).toBe('1e3')})
  test('fails closed when huge represented values make any conversion or railgun leg negligible',()=>{const conversions=stateWith({resources:{housing:d('1e1000'),villages:d('0'),rockets:d('1e1000'),factories:d('1e1000'),spaceFactories:d('0')},parameters:{rocketsPerSpaceFactory:d('1')}});const converted=runDreamConversionsV2(conversions);expect(gameDecimalToCanonicalString(converted.housingToVillages)).toBe('0');expect(gameDecimalToCanonicalString(converted.state.dream.resources.housing)).toBe('1e1000');expect(gameDecimalToCanonicalString(converted.rocketsToSpaceFactories)).toBe('1e1000');const rail=stateWith({resources:{energy:d('10'),railgunCharge:d('10'),dysonPanels:d('10'),swarmPanels:d('1e1000')},parameters:{railgunMaxCharge:d('1')},railgun:{firing:true,fireProgress:0,shotsRemaining:10,activeRailguns:1,reservedPanels:d('10')}});const fired=advanceDreamRailgunV2(rail,.1,GAME_DECIMAL_ONE);expect(fired.roundsFired).toBe(0);expect(gameDecimalToCanonicalString(fired.state.dream.resources.railgunCharge)).toBe('1e1');expect(gameDecimalToCanonicalString(fired.state.dream.railgun.reservedPanels)).toBe('1e1')})
  test('rejects forged acceleration on every public Dream time kernel',()=>{const source=stateWith({resources:{hunters:d('1'),spaceFactories:d('1')}}),forged=gameDecimalFromNumber(2);expect(advanceDreamFoundationalV2(source,1,forged).accepted).toBe(false);expect(advanceDreamEducationV2(source,1,forged).accepted).toBe(false);expect(advanceDreamSpaceAgeV2(source,1,forged).accepted).toBe(false);expect(advanceDreamRailgunV2(source,.1,forged).accepted).toBe(false)})
  test('accepts the authoritative multiplier after returned credit leaves enabled false with a positive bank',()=>{const source=stateWith({doubleTime:{unlocked:true,enabled:false,bankSeconds:10,rate:1},resources:{hunters:d('1')}}),slice=advanceV2TimeResourceSlice(source.timeline,'active',1);expect(slice.status).toBe('ready');if(slice.status!=='ready')throw new Error('Expected ready time slice.');expect(slice.effectiveDreamMultiplier).toBe(2);expect(advanceDreamFoundationalV2(source,1,gameDecimalFromNumber(slice.effectiveDreamMultiplier)).accepted).toBe(true)})
  test('rejects an accumulated railgun progress state that would bypass the bounded one-call round cap',()=>{const source=stateWith({resources:{railgunCharge:d('10'),dysonPanels:d('10')},parameters:{railgunMaxCharge:d('1')},railgun:{firing:true,fireProgress:1,shotsRemaining:10,activeRailguns:1,reservedPanels:d('10')}});expect(advanceDreamRailgunV2(source,.1,GAME_DECIMAL_ONE).accepted).toBe(false)})
  test('caps every fixed-price Dream Buy Max at 1000 batches above 1e308',()=>{
    const source=stateWith({influence:'1e1000',resources:{hunters:d('0')},parameters:{hunterCost:d('1')},});const result=purchaseDreamInfluenceV2(source,'hunters','buy-max');expect(result.accepted).toBe(true);expect(result.requestedMode).toBe('buy-max');expect(gameDecimalToCanonicalString(result.batches)).toBe('1e3');expect(gameDecimalToCanonicalString(result.buyMaxBatchCap!)).toBe('1e3');expect(result.reachedBuyMaxBatchCap).toBe(true);expect(gameDecimalToCanonicalString(result.unitsGranted)).toBe('1e3');expect(gameDecimalToCanonicalString(result.quotedCost)).toBe('1e3');expect(gameDecimalToCanonicalString(result.state.dream.resources.hunters)).toBe('1e3');expect(gameDecimalToCanonicalString(result.debited)).toBe('0');const solar=previewDreamInfluencePurchaseModesV2(source,'solar');expect(solar.map(quote=>quote.requestedMode)).toEqual(['buy-1','buy-10','buy-50','buy-100','buy-max']);expect(gameDecimalToCanonicalString(solar.at(-1)!.batches)).toBe('1e3')
  })
  test('keeps dormant Dream authority outside every production root and closes import bypasses',()=>{
    const root=join(dirname(fileURLToPath(import.meta.url)),'..');const violations:string[]=[],authorityViolations:string[]=[]
    for(const path of files(root)){const normalized=path.replaceAll('\\','/'),source=readFileSync(path,'utf8'),isProjectionOwner=relative(root,path).replaceAll('\\','/')==='inspection/frontendSnapshotV2.ts';if(!normalized.endsWith('/simulation/canonicalEventTimeModelV2.ts')&&!normalized.endsWith('/simulation/dreamV2.test.ts'))for(const claim of dreamKernelAuthorityClaims(source,path))authorityViolations.push(`${relative(root,path)} -> ${claim}`);if(normalized.endsWith('.test.ts')||normalized.endsWith('/application/dreamStrangeMatterAuthorityV2.ts'))continue;for(const specifier of specifiers(source,path)){const module=dreamModule(specifier);const allowed=module==='catalog'&&(normalized.endsWith('/simulation/dreamV2.ts')||normalized.endsWith('/simulation/canonicalDreamResetV2.ts'))||module==='core'&&(normalized.endsWith('/simulation/canonicalEventTimeModelV2.ts')||normalized.endsWith('/application/frontendSnapshot.ts')||normalized.endsWith('/ui/gameplay/simulations/SimulationsSurface.tsx'))||normalized.endsWith('/inspection/v2GameRuntime.ts')&&(module==='core'||module==='authority')||isProjectionOwner&&(module==='catalog'||module==='core'||module==='authority');if(module!==null&&!allowed)violations.push(`${relative(root,path)} -> ${specifier}`)}}expect(violations).toEqual([]);expect(authorityViolations).toEqual([])
    for(const source of [`import * as d from './dreamV2'`,`export * from './dreamCatalogV2.mjs?raw#x'`,`void import(\`../application/dreamStrangeMatterAuthorityV2.js\`)`,`const d=require('./dreamV2.cjs#x')`,`import d=require('./dreamV2.ts')`])expect(specifiers(source,'hostile.ts').some(value=>dreamModule(value)!==null)).toBe(true)
    for(const source of [`import {registerCanonicalDreamKernelAuthorityV2ForEventModel as issue} from './dreamV2.js?x#y'`,`import * as d from './dreamV2.mjs';d['prepareCanonicalDreamKernelStateV2']`,`export {prepareCanonicalDreamKernelStateV2 as prepare} from './dreamV2.cjs#x'`,`export * from './dreamV2.jsx?raw'`,`void import('./dreamV2.tsx#x')`,`const {registerCanonicalDreamKernelAuthorityV2ForEventModel}=require('./dreamV2.cts?x')`,`import d=require('./dreamV2.mts')`])expect(dreamKernelAuthorityClaims(source,'hostile.ts')).not.toEqual([])
  })
})

function files(root:string):readonly string[]{const result:string[]=[];const pending=[root];while(pending.length){const dir=pending.pop()!;for(const entry of readdirSync(dir,{withFileTypes:true})){const path=join(dir,entry.name);if(entry.isDirectory())pending.push(path);else if(/\.(?:ts|tsx|mts|cts|js|jsx|mjs|cjs)$/u.test(entry.name))result.push(path)}}return result}
function specifiers(source:string,path:string):readonly string[]{const file=ts.createSourceFile(path,source,ts.ScriptTarget.Latest,true,/\.[jt]sx$/u.test(path)?ts.ScriptKind.TSX:ts.ScriptKind.TS);const result:string[]=[];const add=(node:ts.Expression|undefined)=>{if(node!==undefined&&ts.isStringLiteralLike(node))result.push(node.text)};const visit=(node:ts.Node)=>{if(ts.isImportDeclaration(node)||ts.isExportDeclaration(node))add(node.moduleSpecifier);else if(ts.isImportEqualsDeclaration(node)&&ts.isExternalModuleReference(node.moduleReference))add(node.moduleReference.expression);else if(ts.isCallExpression(node)&&node.arguments.length===1&&(node.expression.kind===ts.SyntaxKind.ImportKeyword||(ts.isIdentifier(node.expression)&&node.expression.text==='require')))add(node.arguments[0]);ts.forEachChild(node,visit)};visit(file);return result}
function dreamModule(value:string):'core'|'catalog'|'authority'|null{const clean=value.replace(/[?#].*$/u,'');if(/(?:^|\/)dreamV2(?:\.[cm]?[jt]sx?|\/|$)/u.test(clean))return'core';if(/(?:^|\/)dreamCatalogV2(?:\.[cm]?[jt]sx?|\/|$)/u.test(clean))return'catalog';if(/(?:^|\/)dreamStrangeMatterAuthorityV2(?:\.[cm]?[jt]sx?|\/|$)/u.test(clean))return'authority';return null}
const DREAM_KERNEL_AUTHORITY_CLAIMS=new Set(['registerCanonicalDreamKernelAuthorityV2ForEventModel','prepareCanonicalDreamKernelStateV2'])
function dreamKernelAuthorityClaims(source:string,path:string):readonly string[]{const file=ts.createSourceFile(path,source,ts.ScriptTarget.Latest,true,/\.[jt]sx$/u.test(path)?ts.ScriptKind.TSX:ts.ScriptKind.TS),claims:string[]=[];const isCore=(node:ts.Expression|undefined)=>node!==undefined&&ts.isStringLiteralLike(node)&&dreamModule(node.text)==='core';const addNamed=(elements:readonly ts.ImportSpecifier[]|readonly ts.ExportSpecifier[])=>{for(const element of elements){const name=(element.propertyName??element.name).text;if(DREAM_KERNEL_AUTHORITY_CLAIMS.has(name))claims.push(name)}};const visit=(node:ts.Node)=>{if(ts.isImportDeclaration(node)&&isCore(node.moduleSpecifier)){const bindings=node.importClause?.namedBindings;if(bindings!==undefined){if(ts.isNamespaceImport(bindings))claims.push('*');else addNamed(bindings.elements)}}else if(ts.isExportDeclaration(node)&&isCore(node.moduleSpecifier)){if(node.exportClause===undefined||ts.isNamespaceExport(node.exportClause))claims.push('*');else addNamed(node.exportClause.elements)}else if(ts.isImportEqualsDeclaration(node)&&ts.isExternalModuleReference(node.moduleReference)&&isCore(node.moduleReference.expression))claims.push('*');else if(ts.isCallExpression(node)&&node.arguments.length===1&&(node.expression.kind===ts.SyntaxKind.ImportKeyword||(ts.isIdentifier(node.expression)&&node.expression.text==='require'))&&isCore(node.arguments[0]))claims.push('*');ts.forEachChild(node,visit)};visit(file);return claims}

describe('Dream V2 sole publication owner',()=>{
  test('publishes a Dream upgrade with one revision and direct Strange Matter debit',()=>{const state=stateWith({strangeMatter:'10'});const publication=Object.freeze({revision:4,state,runtime});const quote=quoteDreamCommandV2(publication,Object.freeze({kind:'dream-upgrade' as const,upgradeId:'hunter1' as const}));const result=commitDreamCommandV2(quote,publication);expect(result).toMatchObject({accepted:true,changed:true,code:'committed',publication:{revision:5}});expect(result.publication).not.toBeNull();expect(result.publication!.state.dream.upgrades.hunter1).toBe(true);expect(gameDecimalToCanonicalString(result.publication!.state.dream.strangeMatter)).toBe('8e0')})
  test('wraps a Reality purchase and publishes its refreshed Decimal runtime in the same outer revision',()=>{const state=stateWith({strangeMatter:'1000'});const publication=Object.freeze({revision:8,state,runtime});const quote=quoteDreamCommandV2(publication,Object.freeze({kind:'reality-upgrade' as const,upgradeId:'translation1'}));expect(gameDecimalToCanonicalString(quote.batches)).toBe('1e0');expect(gameDecimalToCanonicalString(quote.unitsGranted)).toBe('1e0');expect(gameDecimalToCanonicalString(quote.quotedCost)).not.toBe('0');const result=commitDreamCommandV2(quote,publication);expect(result).toMatchObject({accepted:true,publication:{revision:9}});expect(result.publication).not.toBeNull();expect(result.publication!.state.dream.upgrades.translation1).toBe(true);expect(gameDecimalToCanonicalString(result.publication!.state.dream.strangeMatter)).not.toBe('1e3');expect(Object.isFrozen(result.publication!.runtime.dysonEvaluationSnapshot)).toBe(true);expect(result.publication!.runtime).not.toBe(runtime)})
  test('accepts a represented no-op influence purchase without incrementing the outer revision',()=>{const state=stateWith({influence:'1e1000',resources:{hunters:d('1e1000')},parameters:{hunterCost:d('1')}});const publication=Object.freeze({revision:9,state,runtime});const quote=quoteDreamCommandV2(publication,Object.freeze({kind:'influence-purchase' as const,purchaseId:'hunters' as const,mode:'buy-1' as const}));expect(quote).toMatchObject({accepted:true,commandId:'hunters',requestedMode:'buy-1',currencyPath:'$.reality.influence',expectedPublication:{revision:9}});expect(gameDecimalToCanonicalString(quote.batches)).toBe('1e0');expect(gameDecimalToCanonicalString(quote.unitsGranted)).toBe('1e0');expect(gameDecimalToCanonicalString(quote.quotedCost)).toBe('1e0');const result=commitDreamCommandV2(quote,publication);expect(result).toMatchObject({accepted:true,changed:false,publication:{revision:9}})})
  test('allows negligible-free upgrades, education and paid boosts while retaining authored cost',()=>{const upgradeState=stateWith({strangeMatter:'1e1000'}),upgradePublication=Object.freeze({revision:10,state:upgradeState,runtime}),upgrade=quoteDreamCommandV2(upgradePublication,Object.freeze({kind:'dream-upgrade' as const,upgradeId:'hunter1' as const}));expect(gameDecimalToCanonicalString(upgrade.quotedCost)).toBe('2e0');expect(gameDecimalToCanonicalString(upgrade.debitedStrangeMatter)).toBe('0');expect(commitDreamCommandV2(upgrade,upgradePublication).publication!.state.dream.upgrades.hunter1).toBe(true);const educationState=stateWith({influence:'1e1000',education:{engineering:{...base.dream.education.engineering,active:false,complete:false,cost:d('1')}}}),educationPublication=Object.freeze({revision:11,state:educationState,runtime}),education=quoteDreamCommandV2(educationPublication,Object.freeze({kind:'education-start' as const,educationId:'engineering' as const}));expect(gameDecimalToCanonicalString(education.quotedCost)).toBe('1e0');expect(commitDreamCommandV2(education,educationPublication).publication!.state.dream.education.engineering.active).toBe(true);const boostState=stateWith({influence:'1e1000',resources:{hunters:d('1')},parameters:{communityBoostIsFree:false,communityBoostCost:d('1'),communityBoostClock:9,communityBoostDuration:20}}),boostPublication=Object.freeze({revision:12,state:boostState,runtime}),boost=quoteDreamCommandV2(boostPublication,Object.freeze({kind:'boost' as const,boostId:'community' as const}));expect(gameDecimalToCanonicalString(boost.quotedCost)).toBe('1e0');expect(commitDreamCommandV2(boost,boostPublication).publication!.state.dream.parameters.communityBoostClock).toBe(20)})
  test('rejects inherited catalog names and throwing proxies without escaping or invoking getters',()=>{const publication=Object.freeze({revision:1,state:stateWith({strangeMatter:'10'}),runtime});expect(quoteDreamCommandV2(publication,Object.freeze({kind:'dream-upgrade' as const,upgradeId:'toString' as never})).accepted).toBe(false);let getters=0;const throwing=new Proxy({},{ownKeys(){throw new Error('trap')},get(){getters+=1;throw new Error('getter')}});expect(()=>quoteDreamCommandV2(publication,throwing as never)).not.toThrow();expect(quoteDreamCommandV2(publication,throwing as never).accepted).toBe(false);expect(()=>quoteDreamCommandV2(throwing as never,Object.freeze({kind:'dream-upgrade' as const,upgradeId:'hunter1' as const}))).not.toThrow();expect(getters).toBe(0)})
  test('rejects stale/replayed/hostile commands atomically with zero getter calls',()=>{const state=stateWith({strangeMatter:'10'});const publication=Object.freeze({revision:1,state,runtime});const quote=quoteDreamCommandV2(publication,Object.freeze({kind:'dream-upgrade' as const,upgradeId:'hunter1' as const}));expect(commitDreamCommandV2(quote,Object.freeze({revision:2,state,runtime})).code).toBe('stale-publication');expect(commitDreamCommandV2(quote,publication).code).toBe('quote-rejected');let getters=0;const hostile=Object.defineProperty({},'kind',{enumerable:true,get(){getters+=1;return 'dream-upgrade'}});expect(quoteDreamCommandV2(publication,hostile as never).accepted).toBe(false);expect(getters).toBe(0);const failed=commitDreamCommandV2(null as never,hostile as never);expect(failed.publication).toBeNull();expect(getters).toBe(0)})
})
