// <copyright file="Achievements.cs" company="Jan Ivar Z. Carlsen, Sindri Jóelsson">
// Copyright (c) 2016 Jan Ivar Z. Carlsen, Sindri Jóelsson. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace CloudOnce
{
    using System.Collections.Generic;
    using Internal;

    /// <summary>
    /// Provides access to achievements registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class Achievements
    {
        private static readonly UnifiedAchievement s_tenbots = new UnifiedAchievement("tenbots",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "10bots"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIkpjJyrENEAIQAg"
#else
            "tenbots"
#endif
            );

        public static UnifiedAchievement tenbots
        {
            get { return s_tenbots; }
        }

        private static readonly UnifiedAchievement s_fiveassemblylines = new UnifiedAchievement("fiveassemblylines",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "5assemblylines"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIkpjJyrENEAIQAw"
#else
            "fiveassemblylines"
#endif
            );

        public static UnifiedAchievement fiveassemblylines
        {
            get { return s_fiveassemblylines; }
        }

        private static readonly UnifiedAchievement s_twentykactivective = new UnifiedAchievement("twentykactivective",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "20kactive"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIkpjJyrENEAIQBA"
#else
            "twentykactivective"
#endif
            );

        public static UnifiedAchievement twentykactivective
        {
            get { return s_twentykactivective; }
        }

        private static readonly UnifiedAchievement s_twentyplanets = new UnifiedAchievement("twentyplanets",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "20planets"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIkpjJyrENEAIQBQ"
#else
            "twentyplanets"
#endif
            );

        public static UnifiedAchievement twentyplanets
        {
            get { return s_twentyplanets; }
        }

        private static readonly UnifiedAchievement s_surroundstarstenb = new UnifiedAchievement("surroundstarstenb",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "10b"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIkpjJyrENEAIQBg"
#else
            "surroundstarstenb"
#endif
            );

        public static UnifiedAchievement surroundstarstenb
        {
            get { return s_surroundstarstenb; }
        }

        private static readonly UnifiedAchievement s_engulfgalaxy = new UnifiedAchievement("engulfgalaxy",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "galaxy"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIkpjJyrENEAIQBw"
#else
            "engulfgalaxy"
#endif
            );

        public static UnifiedAchievement engulfgalaxy
        {
            get { return s_engulfgalaxy; }
        }

        private static readonly UnifiedAchievement s_galaxyonehundred = new UnifiedAchievement("galaxyonehundred",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "galaxy100"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIkpjJyrENEAIQCA"
#else
            "galaxyonehundred"
#endif
            );

        public static UnifiedAchievement galaxyonehundred
        {
            get { return s_galaxyonehundred; }
        }

        public static readonly UnifiedAchievement[] All =
        {
            s_tenbots,
            s_fiveassemblylines,
            s_twentykactivective,
            s_twentyplanets,
            s_surroundstarstenb,
            s_engulfgalaxy,
            s_galaxyonehundred,
        };

        public static string GetPlatformID(string internalId)
        {
            return s_achievementDictionary.ContainsKey(internalId)
                ? s_achievementDictionary[internalId].ID
                : string.Empty;
        }

        private static readonly Dictionary<string, UnifiedAchievement> s_achievementDictionary = new Dictionary<string, UnifiedAchievement>
        {
            { "tenbots", s_tenbots },
            { "fiveassemblylines", s_fiveassemblylines },
            { "twentykactivective", s_twentykactivective },
            { "twentyplanets", s_twentyplanets },
            { "surroundstarstenb", s_surroundstarstenb },
            { "engulfgalaxy", s_engulfgalaxy },
            { "galaxyonehundred", s_galaxyonehundred },
        };
    }
}
