// <copyright file="Leaderboards.cs" company="Jan Ivar Z. Carlsen, Sindri Jóelsson">
// Copyright (c) 2016 Jan Ivar Z. Carlsen, Sindri Jóelsson. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace CloudOnce
{
    using System.Collections.Generic;
    using Internal;

    /// <summary>
    /// Provides access to leaderboards registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class Leaderboards
    {
        private static readonly UnifiedLeaderboard s_starsSurrounded = new UnifiedLeaderboard("StarsSurrounded",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "starssurrounded"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIkpjJyrENEAIQAQ"
#else
            "StarsSurrounded"
#endif
            );

        public static UnifiedLeaderboard StarsSurrounded
        {
            get { return s_starsSurrounded; }
        }

        private static readonly UnifiedLeaderboard s_prestiged = new UnifiedLeaderboard("prestiged",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "prestige_ids"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIkpjJyrENEAIQCg"
#else
            "prestiged"
#endif
            );

        public static UnifiedLeaderboard prestiged
        {
            get { return s_prestiged; }
        }

        private static readonly UnifiedLeaderboard s_galaxies = new UnifiedLeaderboard("galaxies",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "galaxies"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIkpjJyrENEAIQCQ"
#else
            "galaxies"
#endif
            );

        public static UnifiedLeaderboard galaxies
        {
            get { return s_galaxies; }
        }

        public static string GetPlatformID(string internalId)
        {
            return s_leaderboardDictionary.ContainsKey(internalId)
                ? s_leaderboardDictionary[internalId].ID
                : string.Empty;
        }

        private static readonly Dictionary<string, UnifiedLeaderboard> s_leaderboardDictionary = new Dictionary<string, UnifiedLeaderboard>
        {
            { "StarsSurrounded", s_starsSurrounded },
            { "prestiged", s_prestiged },
            { "galaxies", s_galaxies },
        };
    }
}
