import { readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

export interface NativeReleaseSource {
  readonly schemaVersion: 1
  readonly marketingVersion: string
  readonly defaultReleaseCandidateId: string
  readonly unityBuildFloor: number
}

export interface NativeReleaseMetadata {
  readonly marketingVersion: string
  readonly releaseCandidateId: string
  readonly androidVersionCode: number
  readonly appleBuildNumber: string
}

const SCRIPT_DIRECTORY = dirname(fileURLToPath(import.meta.url))
const WEB_ROOT = resolve(SCRIPT_DIRECTORY, '..')
const SOURCE_PATH = resolve(WEB_ROOT, 'hosts/native-release.json')
const MAX_ANDROID_VERSION_CODE = 2_100_000_000

export function resolveNativeReleaseMetadata(
  source: NativeReleaseSource,
  requestedReleaseCandidateId?: string,
): NativeReleaseMetadata {
  if (source.schemaVersion !== 1) {
    throw new Error(`Unsupported native release schema ${source.schemaVersion}`)
  }
  if (!/^\d+\.\d+\.\d+$/.test(source.marketingVersion)) {
    throw new Error('marketingVersion must use numeric major.minor.patch form')
  }

  const releaseCandidateId =
    requestedReleaseCandidateId ?? source.defaultReleaseCandidateId
  if (!/^\d{10}$/.test(releaseCandidateId)) {
    throw new Error('Release candidate ID must use UTC YYYYMMDDNN')
  }

  const year = Number(releaseCandidateId.slice(0, 4))
  const month = Number(releaseCandidateId.slice(4, 6))
  const day = Number(releaseCandidateId.slice(6, 8))
  const date = new Date(Date.UTC(year, month - 1, day))
  if (
    date.getUTCFullYear() !== year ||
    date.getUTCMonth() !== month - 1 ||
    date.getUTCDate() !== day
  ) {
    throw new Error('Release candidate ID contains an invalid UTC date')
  }

  const androidVersionCode = Number(releaseCandidateId)
  if (
    !Number.isSafeInteger(androidVersionCode) ||
    androidVersionCode <= source.unityBuildFloor ||
    androidVersionCode > MAX_ANDROID_VERSION_CODE
  ) {
    throw new Error(
      `Release candidate ID must be above Unity build ${source.unityBuildFloor} ` +
      `and no greater than Android's ${MAX_ANDROID_VERSION_CODE} limit`,
    )
  }

  return Object.freeze({
    marketingVersion: source.marketingVersion,
    releaseCandidateId,
    androidVersionCode,
    appleBuildNumber:
      `${releaseCandidateId.slice(2, 6)}.` +
      `${releaseCandidateId.slice(6, 8)}.` +
      releaseCandidateId.slice(8, 10),
  })
}

export function renderAndroidReleaseVersion(
  metadata: NativeReleaseMetadata,
): string {
  return [
    '// Generated by scripts/sync-native-release.ts. Do not edit directly.',
    `ext.idsMarketingVersion = "${metadata.marketingVersion}"`,
    `ext.idsReleaseCandidateId = ${metadata.androidVersionCode}`,
    '',
  ].join('\n')
}

export function renderAppleReleaseVersion(
  metadata: NativeReleaseMetadata,
): string {
  return [
    '// Generated by scripts/sync-native-release.ts. Do not edit directly.',
    `MARKETING_VERSION = ${metadata.marketingVersion}`,
    `CURRENT_PROJECT_VERSION = ${metadata.appleBuildNumber}`,
    '// Local Xcode signing supplies these values when manual signing is used.',
    'IDS_DEVELOPMENT_TEAM =',
    'IDS_PROVISIONING_PROFILE_SPECIFIER =',
    '',
  ].join('\n')
}

export function renderElectronReleaseVersion(
  metadata: NativeReleaseMetadata,
): string {
  return `${JSON.stringify({
    buildVersion: metadata.releaseCandidateId,
    extraMetadata: {
      version: metadata.marketingVersion,
      buildVersion: metadata.releaseCandidateId,
    },
  }, null, 2)}\n`
}

export async function syncNativeRelease(
  requestedReleaseCandidateId = process.env.IDS_RELEASE_CANDIDATE_ID,
): Promise<NativeReleaseMetadata> {
  const source = JSON.parse(
    await readFile(SOURCE_PATH, 'utf8'),
  ) as NativeReleaseSource
  const metadata = resolveNativeReleaseMetadata(
    source,
    requestedReleaseCandidateId,
  )

  await Promise.all([
    writeIfChanged(
      resolve(WEB_ROOT, 'hosts/capacitor/android/release-version.gradle'),
      renderAndroidReleaseVersion(metadata),
    ),
    writeIfChanged(
      resolve(WEB_ROOT, 'hosts/capacitor/ios/release-version.xcconfig'),
      renderAppleReleaseVersion(metadata),
    ),
    writeIfChanged(
      resolve(WEB_ROOT, 'hosts/electron/release-version.json'),
      renderElectronReleaseVersion(metadata),
    ),
  ])
  return metadata
}

async function writeIfChanged(path: string, contents: string): Promise<void> {
  try {
    if (await readFile(path, 'utf8') === contents) return
  } catch {
    // A missing generated file is created below. Other write failures remain
    // visible rather than being mistaken for a successful synchronization.
  }
  await writeFile(path, contents, 'utf8')
}

const invokedPath = process.argv[1]
if (
  invokedPath !== undefined &&
  pathToFileURL(resolve(invokedPath)).href === import.meta.url
) {
  const metadata = await syncNativeRelease()
  process.stdout.write(
    `Synced Idle Dyson Swarm ${metadata.marketingVersion} ` +
    `release candidate ${metadata.releaseCandidateId}.\n`,
  )
}
