import { readdirSync,readFileSync } from 'node:fs'
import { dirname,join,relative } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe,expect,test } from 'vitest'
import ts from 'typescript'
import { cloneCanonicalGameStateV2 } from '../game-state/cloneV2'
import { migratePreparedSaveToV2 } from '../game-state/mappingV2'
import type { CanonicalGameStateV2 } from '../game-state/typesV2'
import { gameDecimalFromCanonicalString,gameDecimalFromNumber,gameDecimalToCanonicalString } from '../math/gameDecimal'
import { PreparedSave } from '../save/prepare'
import { deserializeWebSave } from '../save/serialization'
import schema12Web from '../../test/fixtures/schema-12-canonical-idsweb1-first-run.txt?raw'
import { DeveloperOptionsTransactionOwnerV2,registerDeveloperOptionsReceiverAuthorityV2,type DeveloperOptionsPersistenceCandidateV2,type DeveloperOptionsPublicationV2,type DeveloperOptionsTransactionPortV2 } from './developerOptionsTransactionV2'

const migrated=migratePreparedSaveToV2(PreparedSave.fromDecoded(deserializeWebSave(schema12Web)),Object.freeze({kind:'trusted-same-device' as const})),base=migrated.state,runtime=migrated.runtime,d=(value:string)=>value.includes('e')?gameDecimalFromCanonicalString(value):gameDecimalFromNumber(Number(value))
function stateWith(shards:string,matter:string):CanonicalGameStateV2{return cloneCanonicalGameStateV2({...base,quantum:{...base.quantum,availableShards:d(shards),lifetimeEarnedShards:d('999999999')},dream:{...base.dream,strangeMatter:d(matter)}})}
function publication(state=stateWith('100000','500000'),revision=3,purchased=false,enabled=purchased):Readonly<DeveloperOptionsPublicationV2>{return Object.freeze({revision,state,runtime,platform:Object.freeze({developerOptionsPurchased:purchased,developerOptionsEnabled:enabled})})}
function candidateOf(value:Readonly<DeveloperOptionsPublicationV2>):Readonly<DeveloperOptionsPersistenceCandidateV2>{return Object.freeze({kind:'developer-options-persistence-candidate-v2',...value})}
function harness(options:Readonly<{block?:boolean;persistThrows?:'before'|'after';releaseThrows?:boolean;corruptRead?:boolean;deferredBlock?:Promise<boolean>;initial?:Readonly<DeveloperOptionsPersistenceCandidateV2>}>= {}){let stored:Readonly<DeveloperOptionsPersistenceCandidateV2>|null=options.initial??null;const events:string[]=[];const port:DeveloperOptionsTransactionPortV2={async invalidateAndBlockStoredTimeJob(revision){events.push(`block:${revision}`);return options.deferredBlock??options.block??true},persist(candidate){events.push('persist');if(options.persistThrows==='before')throw new Error('disk-before');stored=candidate;if(options.persistThrows==='after')throw new Error('disk-after')},readBack(){events.push('read');return options.corruptRead&&stored!==null?Object.freeze({...stored,revision:stored.revision+1}):stored},releaseStoredTimeBlock(){events.push('release');if(options.releaseThrows)throw new Error('release')}};return{port,events,get stored(){return stored}}}
function ownerFor(source:Readonly<DeveloperOptionsPublicationV2>,io:ReturnType<typeof harness>):DeveloperOptionsTransactionOwnerV2{return new DeveloperOptionsTransactionOwnerV2(source,registerDeveloperOptionsReceiverAuthorityV2(source.platform,io.port))}

describe('Developer Options V2 transaction owner',()=>{
  test('blocks Stored Time before atomically publishing state and receiver-local entitlement',async()=>{const io=harness(),owner=ownerFor(publication(),io),quote=owner.quote(Object.freeze({kind:'purchase-developer-options'}));expect(quote).toMatchObject({accepted:true,code:'ready',sourceRevision:3,expectedCandidate:{kind:'developer-options-persistence-candidate-v2',revision:4,platform:{developerOptionsPurchased:true,developerOptionsEnabled:true}}});const beforeLifetime=owner.snapshot().state.quantum.lifetimeEarnedShards,result=await owner.commit(quote);expect(result).toMatchObject({accepted:true,changed:true,code:'committed'});expect(io.events).toEqual(['block:3','persist','read','release']);expect(gameDecimalToCanonicalString(result.publication.state.quantum.availableShards)).toBe('0');expect(gameDecimalToCanonicalString(result.publication.state.dream.strangeMatter)).toBe('0');expect(result.publication.state.quantum.lifetimeEarnedShards).toEqual(beforeLifetime)})

  test('rejects either unaffordable currency and never mutates lifetime Shards',async()=>{for(const state of [stateWith('99999','500000'),stateWith('100000','499999')]){const io=harness(),owner=ownerFor(publication(state),io),quote=owner.quote(Object.freeze({kind:'purchase-developer-options'}));expect(quote).toMatchObject({accepted:false,code:'unaffordable',expectedCandidate:null});expect(io.events).toEqual([]);expect(owner.snapshot().state.quantum.lifetimeEarnedShards).toEqual(state.quantum.lifetimeEarnedShards)}})

  test('applies negligible-free purchase semantics without minting either account',async()=>{const io=harness(),owner=ownerFor(publication(stateWith('1e1000','1e1000')),io),quote=owner.quote(Object.freeze({kind:'purchase-developer-options'}));expect(quote.accepted).toBe(true);expect(gameDecimalToCanonicalString(quote.debitedShards)).toBe('0');expect(gameDecimalToCanonicalString(quote.debitedStrangeMatter)).toBe('0');const result=await owner.commit(quote);expect(result.accepted).toBe(true);expect(gameDecimalToCanonicalString(result.publication.state.quantum.availableShards)).toBe('1e1000');expect(gameDecimalToCanonicalString(result.publication.state.dream.strangeMatter)).toBe('1e1000')})

  test('free-enables an owned disabled entitlement and rejects only already enabled',async()=>{const source=publication(stateWith('7','9'),12,true,false),io=harness(),owner=ownerFor(source,io),quote=owner.quote(Object.freeze({kind:'purchase-developer-options'}));expect(quote).toMatchObject({accepted:true,operation:'enable',sourceRevision:12});expect(gameDecimalToCanonicalString(quote.quotedShardCost)).toBe('0');const committed=await owner.commit(quote);expect(committed.publication.platform).toEqual({developerOptionsPurchased:true,developerOptionsEnabled:true});expect(committed.publication.state).toEqual(source.state);expect(owner.quote(Object.freeze({kind:'purchase-developer-options'})).code).toBe('already-owned')})

  test('reconciles persist throws against the captured origin or exact candidate',async()=>{const source=publication(),prior=candidateOf(source),beforeIo=harness({persistThrows:'before',initial:prior}),beforeOwner=ownerFor(source,beforeIo),before=await beforeOwner.commit(beforeOwner.quote(Object.freeze({kind:'purchase-developer-options'})));expect(before).toMatchObject({accepted:false,changed:false,code:'persistence-failed',publication:{revision:3}});expect(beforeIo.events).toEqual(['block:3','persist','read','release']);const afterIo=harness({persistThrows:'after',initial:prior}),afterOwner=ownerFor(source,afterIo),after=await afterOwner.commit(afterOwner.quote(Object.freeze({kind:'purchase-developer-options'})));expect(after).toMatchObject({accepted:true,changed:true,code:'committed',publication:{revision:4,platform:{developerOptionsPurchased:true}}})})

  test('never exposes entitlement when Stored Time blocking fails',async()=>{const source=publication(),io=harness({block:false}),owner=ownerFor(source,io),result=await owner.commit(owner.quote(Object.freeze({kind:'purchase-developer-options'})));expect(result).toMatchObject({accepted:false,changed:false,code:'stored-time-block-failed',publication:{platform:{developerOptionsPurchased:false}}});expect(io.events).toEqual(['block:3'])})

  test('fences an indeterminate readback and cannot expose or retry entitlement',async()=>{const source=publication(),io=harness({corruptRead:true}),owner=ownerFor(source,io),result=await owner.commit(owner.quote(Object.freeze({kind:'purchase-developer-options'})));expect(result.code).toBe('indeterminate');expect(result.publication.platform.developerOptionsPurchased).toBe(false);expect(io.events).toEqual(['block:3','persist','read']);expect((await owner.commit(owner.quote(Object.freeze({kind:'purchase-developer-options'})))).code).toBe('indeterminate')})

  test('reports durable entitlement truthfully when releasing the block fails',async()=>{const source=publication(),io=harness({releaseThrows:true}),owner=ownerFor(source,io),result=await owner.commit(owner.quote(Object.freeze({kind:'purchase-developer-options'})));expect(result).toMatchObject({accepted:true,changed:true,code:'committed-fenced',publication:{revision:4,platform:{developerOptionsPurchased:true,developerOptionsEnabled:true}}});expect(owner.snapshot()).toEqual(result.publication);expect(gameDecimalToCanonicalString(result.publication.state.quantum.availableShards)).toBe('0');expect(gameDecimalToCanonicalString(result.publication.state.dream.strangeMatter)).toBe('0');expect((await owner.commit(owner.quote(Object.freeze({kind:'purchase-developer-options'})))).code).toBe('indeterminate')})

  test('serializes commits and rejects stale/replayed quotes',async()=>{let release!:((value:boolean)=>void);const delayed=new Promise<boolean>(resolve=>{release=resolve}),io=harness({deferredBlock:delayed}),owner=ownerFor(publication(),io),first=owner.quote(Object.freeze({kind:'purchase-developer-options'})),stale=owner.quote(Object.freeze({kind:'purchase-developer-options'})),pending=owner.commit(first);expect((await owner.commit(stale)).code).toBe('busy');release(true);expect((await pending).accepted).toBe(true);expect((await owner.commit(stale)).code).toBe('stale-publication');expect((await owner.commit(first)).code).toBe('quote-rejected')})

  test('reloads only the readback-committed local entitlement',async()=>{const io=harness(),owner=ownerFor(publication(),io),committed=await owner.commit(owner.quote(Object.freeze({kind:'purchase-developer-options'}))),reloadIo=harness(),reloaded=ownerFor(committed.publication,reloadIo);expect(reloaded.snapshot()).toEqual(committed.publication);expect(reloaded.quote(Object.freeze({kind:'purchase-developer-options'})).code).toBe('already-owned')})

  test('rejects hostile request, publication, forged authority and port descriptors with zero getters',()=>{let getters=0;const source=publication(),io=harness(),hostileRequest=Object.defineProperty({},'kind',{enumerable:true,get(){getters+=1;return'purchase-developer-options'}}),owner=ownerFor(source,io);expect(owner.quote(hostileRequest as never).code).toBe('invalid-request');const hostilePublication=new Proxy({},{ownKeys(){throw new Error('trap')},get(){getters+=1;throw new Error('getter')}});expect(()=>new DeveloperOptionsTransactionOwnerV2(hostilePublication as never,registerDeveloperOptionsReceiverAuthorityV2(source.platform,io.port))).toThrow();expect(()=>new DeveloperOptionsTransactionOwnerV2(source,Object.freeze({kind:'developer-options-receiver-authority-v2',platform:source.platform}))).toThrow();expect(()=>new DeveloperOptionsTransactionOwnerV2({...source,platform:{developerOptionsPurchased:true,developerOptionsEnabled:true}},registerDeveloperOptionsReceiverAuthorityV2(source.platform,io.port))).toThrow();const hostilePort=Object.defineProperty({},'persist',{enumerable:true,get(){getters+=1;return()=>{}}});expect(()=>registerDeveloperOptionsReceiverAuthorityV2(source.platform,hostilePort as never)).toThrow();expect(getters).toBe(0)})

  test('keeps the transaction owner dormant across JS and TS module syntaxes',()=>{const root=join(dirname(fileURLToPath(import.meta.url)),'..'),violations:string[]=[];for(const path of sourceFiles(root)){const normalized=relative(root,path).replaceAll('\\','/');if(isAllowedDeveloperOptionsImporter(normalized))continue;for(const specifier of moduleSpecifiers(readFileSync(path,'utf8'),path))if(isModule(specifier))violations.push(`${normalized} -> ${specifier}`)}expect(violations).toEqual([]);expect(isAllowedDeveloperOptionsImporter('other/certification/stage7V2/certificationHost.ts')).toBe(false);for(const source of [`import * as d from './developerOptionsTransactionV2'`,`export * from './developerOptionsTransactionV2.mjs?raw#x'`,`void import(\`./developerOptionsTransactionV2.js\`)`,`const d=require('./developerOptionsTransactionV2.cjs#x')`,`import d=require('./developerOptionsTransactionV2.ts')`])expect(moduleSpecifiers(source,'hostile.ts').some(isModule),source).toBe(true)})
})

function sourceFiles(root:string):readonly string[]{const files:string[]=[],pending=[root];while(pending.length>0){const dir=pending.pop()!;for(const entry of readdirSync(dir,{withFileTypes:true})){const path=join(dir,entry.name);if(entry.isDirectory())pending.push(path);else if(!isExactStage6HarnessPath(root,path)&&/\.(?:ts|tsx|mts|cts|js|jsx|mjs|cjs)$/u.test(entry.name))files.push(path)}}return files}
function isExactStage6HarnessPath(root:string,path:string):boolean{return relative(join(root,'..'),path).replaceAll('\\','/')==='src/simulation/stage6V2EndToEnd.test.ts'}
function moduleSpecifiers(source:string,path:string):readonly string[]{const file=ts.createSourceFile(path,source,ts.ScriptTarget.Latest,true,/\.[jt]sx$/u.test(path)?ts.ScriptKind.TSX:ts.ScriptKind.TS),result:string[]=[];const add=(node:ts.Expression|undefined)=>{if(node!==undefined&&ts.isStringLiteralLike(node))result.push(node.text)};const visit=(node:ts.Node)=>{if(ts.isImportDeclaration(node)||ts.isExportDeclaration(node))add(node.moduleSpecifier);else if(ts.isImportEqualsDeclaration(node)&&ts.isExternalModuleReference(node.moduleReference))add(node.moduleReference.expression);else if(ts.isCallExpression(node)&&node.arguments.length===1&&(node.expression.kind===ts.SyntaxKind.ImportKeyword||(ts.isIdentifier(node.expression)&&node.expression.text==='require')))add(node.arguments[0]);ts.forEachChild(node,visit)};visit(file);return result}
function isModule(value:string):boolean{return /(?:^|\/)developerOptionsTransactionV2(?:\.[cm]?[jt]sx?|\/|$)/u.test(value.replace(/[?#].*$/u,''))}
function isAllowedDeveloperOptionsImporter(path:string):boolean{return new Set(['application/developerOptionsTransactionV2.ts','application/developerOptionsTransactionV2.test.ts','certification/stage7V2/certificationHost.ts','certification/stage7V2/certificationHost.test.ts']).has(path)}
test('Developer guard exempts only the exact Stage 6 harness path',()=>{const root=join(dirname(fileURLToPath(import.meta.url)),'..');expect(isExactStage6HarnessPath(root,join(root,'simulation','stage6V2EndToEnd.test.ts'))).toBe(true);expect(isExactStage6HarnessPath(root,join(root,'hostile','stage6V2EndToEnd.test.ts'))).toBe(false)})
