import { useEffect, useId, useRef, useState } from 'react'
import { useIntl } from 'react-intl'
import { useMediaQuery } from '../../accessibility/useMediaQuery'
import type { DeepReadonly } from '../../../core/contracts'
import type { FrontendGameplaySnapshot } from '../../../application/frontendSnapshot'
import type { CanonicalPlayerCommand } from '../../../application/canonicalPlayerCommands'
import type { UiRuntimePlayerCommandResult } from '../../runtime'
import type { EnabledLocale } from '../../i18n/localeRegistry'
import type { FarmingRecipe, FarmingResource, FarmingState } from '../../../game-state/types'
import { formatGameDuration } from '../../i18n/formatters'
import { Button, InlineResourceAmount, Progress, ProgressControlsPanel } from '../../components'
import { CIVILIZATION_FOCUSES } from '../../../simulation/civilization'
import { FARMING_ROWS, FARMING_RESOURCES, FARMING_TUNING as T, farmingWorkers, farmingCapacity, farmingGoal, farmingGoalRecipe, farmingGranaryCost, farmingGranaryPurchaseStatus, FARMING_BUILDINGS, farmingJobForRow, farmingRowUnlocked, farmingLaborShares, farmingComplete, farmingMilestoneFlags, type FarmingRow } from '../../../simulation/farming'
import { realTimeDuration } from '../effectiveSpeed'
import { CivilizationSymbol } from './CivilizationSymbol'
import { FarmingSymbol, type FarmingSymbolId } from './FarmingSymbol'
import { civilizationMessages as c } from './civilizationMessages'
import { farmingMessages as m } from './farmingMessages'

type Props={gameplay:DeepReadonly<FrontendGameplaySnapshot>;locale:EnabledLocale;gameSpeed:number;dispatchPlayer:(command:CanonicalPlayerCommand)=>Promise<UiRuntimePlayerCommandResult>}
export function FarmingSurface({gameplay,locale,gameSpeed,dispatchPlayer}:Props){
 const scrollHeading=useMediaQuery('(max-width: 480px)')
 const intl=useIntl(),f=gameplay.progression.civilization!.farming! as FarmingState,camp=gameplay.progression.civilization!
 const [open,setOpen]=useState(false),[pending,setPending]=useState(false),[failed,setFailed]=useState(false),id=useId(),busy=useRef(false),restore=useRef<HTMLButtonElement|null>(null)
 useEffect(()=>{if(!pending&&restore.current){restore.current.focus();restore.current=null}},[pending])
 const action=async(command:CanonicalPlayerCommand)=>{if(busy.current)return;busy.current=true;setPending(true);setFailed(false);try{if((await dispatchPlayer(command)).status!=='accepted')setFailed(true)}catch{setFailed(true)}finally{busy.current=false;setPending(false)}}
 const msg=(key:keyof typeof m,values?:Record<string,string|number>)=>intl.formatMessage(m[key],values)
 const number=(value:number|bigint)=>intl.formatNumber(value,{maximumFractionDigits:1}),name=(r:FarmingResource)=>r==='goods'?msg('goods'):intl.formatMessage(c[r])
 const amount=(r:FarmingSymbolId,value:number|bigint,affordable=true,label?:string)=><span className="civilization-icon-amount" role="img" aria-label={msg('amount',{resource:label??(r==='worker'?msg('workers'):FARMING_RESOURCES.includes(r as FarmingResource)?name(r as FarmingResource):msg(r as keyof typeof m)),value:number(value)})} data-affordable={affordable}><InlineResourceAmount leadingSymbol={<FarmingSymbol resource={r}/>} value={(r==='worker'&&label===msg('crew')&&typeof value==='number'&&!Number.isInteger(value)?'≈':'')+number(value)}/></span>
 const recipe=(inputs:FarmingRecipe)=>intl.formatList(Object.entries(inputs).map(([r,n])=>msg('amount',{resource:name(r as FarmingResource),value:number(n!)})))
 const goal=farmingGoal(f),goalName=goal.kind==='home'?msg('home',{value:goal.index!+1}):goal.kind==='repair'?msg('repair',{value:goal.index!+1}):goal.kind==='ship'?msg('ship'):msg(goal.kind)
 const active=f.phase==='farming',complete=farmingComplete(f),speed=1+(gameplay.progression.challenges?.galvanizedSkillIds?.length??0)*.05,shares=farmingLaborShares(f),cost=farmingGranaryCost(f)
 const focusNames={balanced:m.balanced,provisioning:m.supplies,settlement:m.growth,expeditions:m.travel}
 const focus=<div className="civilization-focus"><div className="civilization-focus-heading"><span data-total-workers>{amount('worker',farmingWorkers(f))}</span></div><div className="civilization-focus-options" role="radiogroup" aria-label={msg('focus')}>{CIVILIZATION_FOCUSES.map((key,index)=><button key={key} type="button" role="radio" data-focus={key} aria-checked={f.focus===key} tabIndex={f.focus===key?0:-1} disabled={pending||!active} onClick={event=>{if(key!==f.focus){restore.current=event.currentTarget;void action({kind:'civilization.farming-focus',focus:key})}}} onKeyDown={event=>{if(pending||!active||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home','End'].includes(event.key))return;event.preventDefault();const next=event.key==='Home'?0:event.key==='End'?3:(index+(['ArrowRight','ArrowDown'].includes(event.key)?1:3))%4,key=CIVILIZATION_FOCUSES[next],button=event.currentTarget.parentElement?.querySelector<HTMLButtonElement>(`[data-focus="${key}"]`);if(button)restore.current=button;if(key!==f.focus)void action({kind:'civilization.farming-focus',focus:key});button?.focus()}}>{intl.formatMessage(focusNames[key])}</button>)}</div></div>
 const rowRecipe=(row:FarmingRow):{inputs:FarmingRecipe;output:number;symbol:FarmingSymbolId;work:number}=>{
  const job=farmingJobForRow(f,row);if(job)return {inputs:job.inputs,output:job.kind==='home'||job.kind==='repair'?2:job.kind==='ship'?1:job.output||1,symbol:job.kind==='home'||job.kind==='repair'?'worker':job.kind==='ship'?'hall':job.kind as FarmingSymbolId,work:job.work}
  if(row==='fields')return {inputs:{},output:12*(f.completedBuildings.includes('pasture')?1.5:1)*(f.completedBuildings.includes('waterworks')?1.25:1)*(f.completedBuildings.includes('intensiveCultivation')?1.2:1),symbol:'food',work:42}
  if(row==='woodlot')return {inputs:{},output:8,symbol:'materials',work:42}
  if(row==='workshop')return {inputs:{materials:6},output:2,symbol:'tools',work:42}
  if(row==='homes'){const g=goal.kind==='repair'?goal:{kind:'home' as const,index:Math.min(5,f.homesBuilt)};return {...farmingGoalRecipe(f,g),output:2,symbol:'worker'}}
  if(row==='kiln'&&f.completedBuildings.includes('kiln'))return {inputs:{materials:f.completedBuildings.includes('guildWorkshop')?6:4},output:f.completedBuildings.includes('guildWorkshop')?3:2,symbol:'goods',work:63}
  if(row==='hall'&&f.completedBuildings.includes('hall'))return {inputs:{food:350,goods:35},output:1,symbol:'hall',work:f.completedBuildings.includes('townMarket')?1512:1890}
  return {...T.buildings[row as keyof typeof T.buildings],output:1,symbol:row}
 }
 const unlockHint=(row:FarmingRow)=>msg(row==='workshop'||row==='homes'?'firstHarvest':row==='pasture'||row==='kiln'?'oneGranary':row==='waterworks'?'kilnNeeded':row==='intensiveCultivation'?'cultivationNeeded':row==='guildWorkshop'?'guildNeeded':row==='townMarket'?'marketNeeded':'hallNeeded')
 const rows=(ids:readonly FarmingRow[])=>ids.filter(row=>farmingRowUnlocked(f,row)).map(row=>{
  const job=farmingJobForRow(f,row),r=rowRecipe(row),key=row==='fields'?'food':row==='woodlot'?'materials':row==='workshop'?'tools':job?.kind==='ship'?'ship':job?.kind==='goods'?'goods':'build',labor=job?shares[key]??0:0
  const shipment=job?.kind==='ship'||row==='hall'&&f.completedBuildings.includes('hall')
  const shipmentMaterials=shipment?(job?.kind==='ship'?job.output:f.completedBuildings.includes('townMarket')?100:80):0
  const finite=FARMING_BUILDINGS.includes(row as typeof FARMING_BUILDINGS[number])&&row!=='kiln'&&row!=='hall'&&f.completedBuildings.includes(row as typeof FARMING_BUILDINGS[number]),homesDone=row==='homes'&&f.homesBuilt===6&&!f.lostHomes.length
  const seconds=job&&labor>0?job.remainingWork/(labor*speed):Infinity,status=finite||homesDone?msg('done'):Number.isFinite(seconds)?formatGameDuration(locale,realTimeDuration(seconds,gameSpeed),{maximumFractionDigits:1}):row==='fields'&&f.resources.food>=farmingCapacity(f)-1e-8?msg('cap'):msg('waiting')
  return <li key={row}><article className="civilization-activity" data-activity-id={row} data-status={job?'running':finite||homesDone?'complete':'waiting'}><details className="civilization-job"><summary><div className="civilization-job-header"><div className="civilization-job-title"><FarmingSymbol resource={row}/><strong>{msg(row)}</strong>{amount('worker',labor,true,msg('crew'))}</div>{!finite&&!homesDone&&<div className="civilization-job-recipe"><span className="civilization-start-cost" data-reserved={!!job} role="group" aria-label={msg('inputs')}>{Object.entries(r.inputs).map(([resource,n])=><span key={resource}>{amount(resource as FarmingResource,n!,!!job||f.resources[resource as FarmingResource]>=n!)}</span>)}</span>{Object.keys(r.inputs).length>0&&<span className="civilization-recipe-arrow" aria-hidden="true">▶</span>}<span className="civilization-output" role="group" aria-label={msg('outputs')}>{shipment&&amount('materials',shipmentMaterials)}{amount(r.symbol,r.output,true,shipment?msg('connection'):undefined)}</span></div>}</div>{finite||homesDone?<span className="farming-row-complete">{msg('done')}</span>:<div className="civilization-cycle"><Progress className="civilization-cycle-progress" label={msg(row)} value={job?job.work-job.remainingWork:0} maximum={r.work} valueText={status}/><span className="civilization-job-timer">{Number.isFinite(seconds)?status:'∞'}</span></div>}{row==='homes'&&weather}<span className="civilization-chevron" aria-hidden="true">›</span></summary><div className="civilization-activity-details"><dl className="civilization-facts civilization-recipe"><div><dt>{msg('inputs')}</dt><dd>{recipe(r.inputs)||'—'}</dd></div><div><dt>{msg('outputs')}</dt><dd>{shipment&&<>{recipe({materials:shipmentMaterials})}, </>}{msg('amount',{resource:shipment?msg('connection'):r.symbol==='worker'?msg('workers'):FARMING_RESOURCES.includes(r.symbol as FarmingResource)?name(r.symbol as FarmingResource):msg(r.symbol as keyof typeof m),value:number(r.output)})}</dd></div><div><dt>{msg('crew')}</dt><dd>{number(labor)}</dd></div><div><dt>{intl.formatMessage(c.duration)}</dt><dd>{msg('work',{value:number(r.work)})}</dd></div></dl><p>{job?msg('paid'):finite||homesDone?msg('finite'):status}</p><p>{msg('averageLabor')}</p>{row==='homes'&&<><p>{msg('homeEffect')}</p><p>{msg('weatherHelp')}</p></>}{row==='hall'&&<p>{msg('yield',{materials:number(shipmentMaterials)})}</p>}{row==='intensiveCultivation'&&<p>{msg('cultivationEffect')}</p>}{row==='guildWorkshop'&&<p>{msg('guildEffect')}</p>}{row==='townMarket'&&<p>{msg('marketEffect')}</p>}</div></details></article></li>
 })
 const stock=<details className="civilization-stock"><summary><dl className="civilization-balances">{FARMING_RESOURCES.map(resource=><div key={resource}><dt><span className="ui-visually-hidden">{name(resource)}</span><FarmingSymbol resource={resource}/></dt><dd>{number(f.resources[resource])}{resource==='food'&&<> / {number(farmingCapacity(f))}</>}</dd></div>)}</dl><span className="civilization-chevron" aria-hidden="true">›</span></summary><dl className="civilization-resource-legend">{FARMING_RESOURCES.map(resource=><div key={resource}><dt><FarmingSymbol resource={resource}/><span>{name(resource)}</span></dt><dd>{number(f.resources[resource])}{resource==='food'&&<> / {number(farmingCapacity(f))}</>}</dd></div>)}</dl></details>
 const purchase=farmingGranaryPurchaseStatus(f)
 const missing=Object.fromEntries(Object.entries(cost).filter(([resource,n])=>f.resources[resource as FarmingResource]<n!).map(([resource,n])=>[resource,n!-f.resources[resource as FarmingResource]])) as FarmingRecipe
 const reason=purchase==='firstHome'?'granaryFirstHome':purchase==='maximum'?'granaryMaximum':purchase==='inputs'?'granaryInputs':purchase==='repairReserve'?'granaryRepairReserve':'granaryInactive'
 const buyLabel=purchase==='ready'||purchase==='inputs'?'buy':purchase==='repairReserve'?'reserved':purchase==='maximum'?'limit':purchase==='inactive'?'closed':'locked'
 const granary=<section className="farming-granary"><details><summary aria-label={msg('granaryDetails')} id={id+'-purchase'}><div className="farming-purchase-title"><FarmingSymbol resource="granary"/><strong>{msg('granary')}</strong><span aria-label={msg('owned',{value:number(f.granaries)})}>×{number(f.granaries)}</span></div><div className="farming-purchase-values"><span className="civilization-start-cost farming-granary-cost" role="group" aria-label={msg('nextPrice')}>{Object.entries(cost).map(([r,n])=><span key={r}>{amount(r as FarmingResource,n!,f.resources[r as FarmingResource]>=n!)}</span>)}</span><span className="civilization-recipe-arrow" aria-hidden="true">▶</span><span className="civilization-output farming-storage-benefit" role="group" aria-label={msg('compactStorage')}><FarmingSymbol resource="food"/>{msg('compactStorage')}</span></div></summary><div className="farming-purchase-details"><p>{msg('owned',{value:number(f.granaries)})}</p><p>{msg('storageGain',{value:number(farmingCapacity(f))})}</p><p>{msg('nextPrice')}: {recipe(cost)}</p><p>{msg('granaryEffect')}</p>{purchase!=='ready'&&<p role="status" data-purchase-blocked={purchase}>{purchase==='inputs'?msg('missingInputs',{inputs:recipe(missing)}):msg(reason)}</p>}{active&&goal.kind==='granary'&&<p role="status">{msg('manual')}</p>}</div></details><Button variant="purchase" state={pending?'pending':failed?'failure':'idle'} disabled={pending||purchase!=='ready'} aria-describedby={id+'-purchase'} aria-label={msg('build')} onClick={()=>void action({kind:'civilization.build-granary'})}>{msg(buyLabel)}</Button></section>
 const weather=<div className="farming-weather" data-risk={f.weathering>=75}><Progress label={msg(f.weathering>=75?'risk':'housingWeathering')} value={f.weathering} maximum={100} valueText={number(f.weathering)+' / 100'}/></div>
 const shop=<section className="farming-shop" aria-label={msg('shop')}><h3>{msg('shop')}</h3>{granary}</section>
 const established=FARMING_BUILDINGS.filter(row=>f.completedBuildings.includes(row))
 const constructed=established.length>0&&<section className="farming-constructed"><h3>{msg('constructed')}</h3><p>{msg('automatic')}</p><ul>{established.map(row=>{const effect=row==='intensiveCultivation'?'cultivationEffect':row==='guildWorkshop'?'guildEffect':row==='townMarket'?'marketEffect':null;return <li key={row}>{effect?<details className="farming-upgrade-details"><summary><FarmingSymbol resource={row}/><strong>{msg(row)}</strong><span>{msg('done')}</span></summary><p>{msg(effect)}</p></details>:<><FarmingSymbol resource={row}/><strong>{msg(row)}</strong><span>{msg('done')}</span></>}</li>})}</ul></section>
 const eraHeader=<div className="civilization-era-header"><header className="civilization-heading"><h2>{msg('era')}</h2><strong className="civilization-fracture">{msg('boost',{value:number((speed-1)*100)})}</strong></header><div className="farming-housing-status"><span>{msg('homesCount')}: {number(f.homes.length)} / 6</span><span>{msg('connection')}: {number(f.shipments)} / 6</span></div>{f.lostHomes.length>0&&<p role="status" className="farming-warning">{msg('lost')}</p>}</div>
 return <section className="simulations-surface civilization-surface farming-surface" data-era="information" data-farming-phase={f.phase} data-scroll-heading={scrollHeading||undefined} aria-label={msg('era')}>{!scrollHeading&&eraHeader}<div className="civilization-scroll">{scrollHeading&&eraHeader}
 {f.phase==='settling-forager'?<section className="civilization-preview"><p>{msg('settling')}</p></section>:f.phase==='complete'?<section className="civilization-preview"><h3>{msg('complete')}</h3><p>{msg('finished')}</p><p>{msg('betaEndpoint')}</p>{stock}</section>:<>{stock}{shop}<div className="civilization-paths"><section className="civilization-path"><h3>{msg('production')}</h3><ol className="civilization-activities">{rows(['fields','woodlot','workshop'])}</ol></section><section className="civilization-path"><h3>{msg('village')}</h3><ol className="civilization-activities">{rows(FARMING_ROWS.filter(row=>!['fields','woodlot','workshop'].includes(row)&&!(!['kiln','hall'].includes(row)&&f.completedBuildings.includes(row as typeof FARMING_BUILDINGS[number]))))}</ol>{constructed}</section></div>{complete&&active&&<section className="civilization-preview"><Button fullWidth disabled={pending} onClick={()=>void action({kind:'civilization.complete-farming'})}>{msg('finish')}</Button></section>}{f.phase==='settling-village'&&<p className="civilization-preview">{msg('pendingFinish')}</p>}</>}
 <details className="civilization-stock farming-source"><summary><strong>{msg('source')}</strong><span className="civilization-chevron" aria-hidden="true">›</span></summary><p>{msg('export',{workers:number(camp.workers),food:number(f.inheritedFoodPerMinute),materials:number(f.inheritedMaterialsPerMinute)})}</p></details>
 </div><footer className="simulations-surface__footer civilization-dock"><ProgressControlsPanel className="civilization-control-panel ui-progress-controls-panel--production-summary" ariaLabel={msg('stage')} expanded={open} controlsId={id} settingsLabel={msg('settings')} onExpandedChange={setOpen} aboveSummary={<>{focus}{failed&&<p role="alert">{msg('failed')}</p>}</>} summary={<div className="civilization-catalyst-summary"><Progress label={<span className="civilization-goal-label"><CivilizationSymbol resource="catalyst"/>{msg('stage')}</span>} value={farmingMilestoneFlags(f).filter(Boolean).length/6} valueText={number(farmingMilestoneFlags(f).filter(Boolean).length)+' / 6'}/></div>}>
 {active&&<p className="farming-settings-copy">{msg('next',{name:goalName})}</p>}<details className="civilization-workforce"><summary><strong>{msg('crew')}</strong><span className="civilization-chevron" aria-hidden="true">›</span></summary><div className="civilization-camp-details"><dl className="civilization-facts">{Object.entries(shares).map(([key,n])=><div key={key}><dt>{key==='food'?msg('fields'):key==='materials'?msg('woodlot'):key==='tools'?msg('workshop'):key==='goods'?msg('kiln'):key==='ship'?msg('ship'):goalName}</dt><dd>{number(n)}</dd></div>)}</dl><p>{msg('averageLabor')}</p><p>{msg('focusEffect')}</p><p>{msg('weatherHelp')}</p></div></details>
 {FARMING_ROWS.some(row=>!farmingRowUnlocked(f,row))&&<section className="civilization-upcoming"><h3>{msg('upcoming')}</h3><dl>{FARMING_ROWS.filter(row=>!farmingRowUnlocked(f,row)).map(row=><div key={row}><dt>{msg(row)}</dt><dd>{unlockHint(row)}</dd></div>)}</dl></section>}
 {f.skillRewardPending&&<p role="status" className="farming-settings-copy">{msg('pendingSkill')}</p>}<p className="farming-settings-copy">{msg('skillLimit')}</p>
 </ProgressControlsPanel></footer></section>
}
